CREATE TABLE [dbo].[BatchUploadedClaims] (
    [BatchUploadedClaimID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [BatchID]              BIGINT         NULL,
    [BatchTypeID]          BIGINT         NULL,
    [PayorID]              BIGINT         NULL,
    [ReferralID]           BIGINT         NULL,
    [Bill_NPI]             NVARCHAR (100) NULL,
    [Bill_TaxID]           NVARCHAR (100) NULL,
    [ClaimID]              NVARCHAR (100) NULL,
    [ClaimMD_ID]           NVARCHAR (100) NULL,
    [FDOS]                 NVARCHAR (100) NULL,
    [FileID]               NVARCHAR (100) NULL,
    [FileName]             NVARCHAR (100) NULL,
    [INS_Number]           NVARCHAR (100) NULL,
    [PayerID]              NVARCHAR (100) NULL,
    [PCN]                  NVARCHAR (100) NULL,
    [Remote_ClaimID]       NVARCHAR (100) NULL,
    [Sender_ICN]           NVARCHAR (100) NULL,
    [Sender_Name]          NVARCHAR (100) NULL,
    [SenderID]             NVARCHAR (100) NULL,
    [Status]               NVARCHAR (100) NULL,
    [Total_Charge]         NVARCHAR (100) NULL,
    [PatientName]          NVARCHAR (100) NULL,
    [Payer]                NVARCHAR (100) NULL,
    [BillingProvider]      NVARCHAR (100) NULL,
    [CreatedDate]          DATETIME       NULL,
    [CreatedBy]            BIGINT         NULL,
    [UpdatedDate]          DATETIME       NULL,
    [UpdatedBy]            BIGINT         NULL,
    [SystemID]             NVARCHAR (MAX) NULL,
    [MessageStr]           NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_BatchClaims] PRIMARY KEY CLUSTERED ([BatchUploadedClaimID] ASC)
);

