CREATE TABLE [dbo].[Edi277FileDetails] (
    [Edi277FileDetailID]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [Edi277FileID]        BIGINT        NOT NULL,
    [Source]              VARCHAR (MAX) NULL,
    [TraceNumber]         VARCHAR (MAX) NULL,
    [ReceiptDate]         VARCHAR (MAX) NULL,
    [ProcessDate]         VARCHAR (MAX) NULL,
    [Receiver]            VARCHAR (MAX) NULL,
    [TotalAcceptedClaims] VARCHAR (MAX) NULL,
    [TotalAcceptedAmount] VARCHAR (MAX) NULL,
    [TotalRejectedClaims] VARCHAR (MAX) NULL,
    [TotalRejectedAmount] VARCHAR (MAX) NULL,
    [Provider]            VARCHAR (MAX) NULL,
    [LastName]            VARCHAR (MAX) NULL,
    [FirstName]           VARCHAR (MAX) NULL,
    [AHCCCSID]            VARCHAR (MAX) NULL,
    [Status]              VARCHAR (MAX) NULL,
    [CSCC]                VARCHAR (MAX) NULL,
    [CSC]                 VARCHAR (MAX) NULL,
    [EIC]                 VARCHAR (MAX) NULL,
    [Action]              VARCHAR (MAX) NULL,
    [Amount]              VARCHAR (MAX) NULL,
    [Message]             VARCHAR (MAX) NULL,
    [BatchNoteID]         VARCHAR (MAX) NULL,
    [BatchID]             VARCHAR (MAX) NULL,
    [NoteID]              VARCHAR (MAX) NULL,
    [ClaimNumber]         VARCHAR (MAX) NULL,
    [PayorClaimNumber]    VARCHAR (MAX) NULL,
    [ServiceDate]         VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Edi277FileDetails] PRIMARY KEY CLUSTERED ([Edi277FileDetailID] ASC)
);

