CREATE TABLE [dbo].[Facilities] (
    [FacilityID]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [FacilityName]            VARCHAR (100) NULL,
    [FacilityBillingName]     VARCHAR (100) NULL,
    [Address]                 VARCHAR (100) NULL,
    [City]                    VARCHAR (50)  NULL,
    [State]                   VARCHAR (10)  NULL,
    [ZipCode]                 VARCHAR (15)  NULL,
    [Phone]                   VARCHAR (15)  NULL,
    [Cell]                    VARCHAR (15)  NULL,
    [RegionID]                BIGINT        NULL,
    [County]                  VARCHAR (50)  NULL,
    [GSA]                     INT           NULL,
    [BadCapacity]             INT           NULL,
    [PrivateRoomCount]        INT           NULL,
    [SiteType]                VARCHAR (100) NULL,
    [ProviderType]            VARCHAR (50)  NULL,
    [Licensure]               VARCHAR (100) NULL,
    [LicensureRenewalDate]    DATE          NULL,
    [FirePermitDate]          DATE          NULL,
    [NPI]                     VARCHAR (10)  NULL,
    [AHCCCSID]                VARCHAR (6)   NULL,
    [EIN]                     VARCHAR (9)   NULL,
    [FacilityColorScheme]     VARCHAR (10)  NULL,
    [ParentFacilityID]        BIGINT        CONSTRAINT [DF_Facilities_ParentFacilityID] DEFAULT ((0)) NOT NULL,
    [IsDeleted]               BIT           NOT NULL,
    [CreatedBy]               BIGINT        NOT NULL,
    [CreatedDate]             DATETIME      NOT NULL,
    [UpdatedDate]             DATETIME      NOT NULL,
    [UpdatedBy]               BIGINT        NOT NULL,
    [SystemID]                VARCHAR (50)  NOT NULL,
    [DefaultScheduleStatusID] BIGINT        NULL,
    [AgencyID]                BIGINT        NULL,
    CONSTRAINT [PK_Facilities] PRIMARY KEY CLUSTERED ([FacilityID] ASC),
    CONSTRAINT [FK_Facilities_Regions] FOREIGN KEY ([RegionID]) REFERENCES [dbo].[Regions] ([RegionID])
);


GO
create TRIGGER [dbo].[tr_Facilities_Updated] ON [dbo].[Facilities]
FOR UPDATE AS 

INSERT INTO JO_Facilities( 
FacilityID,
FacilityName,
FacilityBillingName,
Address,
City,
State,
ZipCode,
Phone,
Cell,
RegionID,
County,
GSA,
BadCapacity,
PrivateRoomCount,
SiteType,
ProviderType,
Licensure,
LicensureRenewalDate,
FirePermitDate,
NPI,
AHCCCSID,
EIN,
FacilityColorScheme,
ParentFacilityID,
IsDeleted,
CreatedBy,
CreatedDate,
UpdatedDate,
UpdatedBy,
SystemID,
Action,ActionDate
)

SELECT  
FacilityID,
FacilityName,
FacilityBillingName,
Address,
City,
State,
ZipCode,
Phone,
Cell,
RegionID,
County,
GSA,
BadCapacity,
PrivateRoomCount,
SiteType,
ProviderType,
Licensure,
LicensureRenewalDate,
FirePermitDate,
NPI,
AHCCCSID,
EIN,
FacilityColorScheme,
ParentFacilityID,
IsDeleted,
CreatedBy,
CreatedDate,
UpdatedDate,
UpdatedBy,
SystemID,
'U',GETUTCDATE() FROM deleted