CREATE TABLE [dbo].[JO_Employees] (
    [JO_EmployeeID]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [EmployeeID]                  BIGINT        NULL,
    [FirstName]                   VARCHAR (50)  NULL,
    [MiddleName]                  VARCHAR (50)  NULL,
    [LastName]                    VARCHAR (50)  NULL,
    [Email]                       VARCHAR (50)  NULL,
    [UserName]                    VARCHAR (50)  NULL,
    [Password]                    VARCHAR (100) NULL,
    [PasswordSalt]                VARCHAR (MAX) NULL,
    [PhoneWork]                   VARCHAR (20)  NULL,
    [PhoneHome]                   VARCHAR (20)  NULL,
    [DepartmentID]                BIGINT        NULL,
    [IsDepartmentSupervisor]      BIT           NULL,
    [SecurityQuestionID]          BIGINT        NULL,
    [SecurityAnswer]              VARCHAR (50)  NULL,
    [IsActive]                    BIT           NULL,
    [IsVerify]                    BIT           NULL,
    [RoleID]                      BIGINT        NULL,
    [IsSecurityQuestionSubmitted] BIT           NULL,
    [CreatedDate]                 DATETIME      NULL,
    [CreatedBy]                   BIGINT        NULL,
    [UpdatedDate]                 DATETIME      NULL,
    [UpdatedBy]                   BIGINT        NULL,
    [SystemID]                    VARCHAR (100) NULL,
    [IsDeleted]                   BIT           NULL,
    [EmpSignature]                VARCHAR (MAX) NULL,
    [EmployeeSignatureID]         BIGINT        NULL,
    [CredentialID]                VARCHAR (50)  NULL,
    [Degree]                      VARCHAR (100) NULL,
    [Action]                      CHAR (1)      NULL,
    [ActionDate]                  DATETIME      NULL,
    [RegularHours]                DECIMAL (18)  NULL,
    [RegularPayHours]             FLOAT (53)    NULL,
    [OvertimePayHours]            FLOAT (53)    NULL,
    CONSTRAINT [PK_JO_Employees] PRIMARY KEY CLUSTERED ([JO_EmployeeID] ASC)
);

