CREATE TABLE [dbo].[OrganizationSettings] (
    [OrganizationID]                                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [SiteLogo]                                         NVARCHAR (MAX) NULL,
    [SiteName]                                         NVARCHAR (100) NULL,
    [SiteBaseUrl]                                      NVARCHAR (200) NULL,
    [SupportEmail]                                     NVARCHAR (100) NULL,
    [PageSize]                                         INT            NULL,
    [NetworkHost]                                      NVARCHAR (100) NULL,
    [NetworkPort]                                      NVARCHAR (10)  NULL,
    [FromTitle]                                        NVARCHAR (100) NULL,
    [FromEmail]                                        NVARCHAR (100) NULL,
    [FromEmailPassword]                                NVARCHAR (100) NULL,
    [EnableSSL]                                        BIT            NULL,
    [TwilioAccountSID]                                 NVARCHAR (100) NULL,
    [TwilioAuthToken]                                  NVARCHAR (100) NULL,
    [TwilioServiceSID]                                 NVARCHAR (100) NULL,
    [TwilioFromNo]                                     NVARCHAR (20)  NULL,
    [CreatedDate]                                      DATETIME       NULL,
    [CreatedBy]                                        BIGINT         NULL,
    [UpdatedDate]                                      DATETIME       NULL,
    [UpdatedBy]                                        BIGINT         NULL,
    [SystemID]                                         NVARCHAR (MAX) NULL,
    [FavIcon]                                          NVARCHAR (MAX) NULL,
    [LoginScreenLogo]                                  NVARCHAR (MAX) NULL,
    [GoogleRecaptchaKey]                               NVARCHAR (100) NULL,
    [TimeZone]                                         NVARCHAR (200) NULL,
    [TemplateLogo]                                     NVARCHAR (MAX) NULL,
    [AndroidMinimumVersion]                            VARCHAR (100)  NULL,
    [AndroidCurrentVersion]                            VARCHAR (100)  NULL,
    [IOSMinimumVersion]                                VARCHAR (100)  NULL,
    [IOSCurrentVersion]                                VARCHAR (100)  NULL,
    [Submitter_NM103_NameLastOrOrganizationName]       VARCHAR (MAX)  NULL,
    [Submitter_NM109_IdCode]                           VARCHAR (100)  NULL,
    [Submitter_EDIContact1_PER02_Name]                 VARCHAR (MAX)  NULL,
    [Submitter_EDIContact1_PER04_CommunicationNumber]  VARCHAR (20)   NULL,
    [Submitter_EDIContact1_PER08_CommunicationNumber]  VARCHAR (200)  NULL,
    [BillingProvider_NM103_NameLastOrOrganizationName] VARCHAR (MAX)  NULL,
    [BillingProvider_NM109_IdCode]                     VARCHAR (100)  NULL,
    [BillingProvider_N301_Address]                     VARCHAR (MAX)  NULL,
    [BillingProvider_N401_City]                        VARCHAR (100)  NULL,
    [BillingProvider_N402_State]                       VARCHAR (100)  NULL,
    [BillingProvider_N403_Zipcode]                     VARCHAR (20)   NULL,
    [BillingProvider_REF02_ReferenceIdentification]    VARCHAR (100)  NULL,
    [TwilioDefaultCountryCode]                         VARCHAR (10)   NULL,
    [PatientResignatureNeeded]                         BIT            CONSTRAINT [DF__Organizat__Patie__5F3F01E1] DEFAULT ((0)) NOT NULL,
    [InvoiceGenerationFrequency]                       INT            CONSTRAINT [DF__Organizat__Invoi__7345FA8E] DEFAULT ((1)) NOT NULL,
    [InvoiceNote]                                      NVARCHAR (MAX) NULL,
    [InvoiceTaxRate]                                   DECIMAL (5, 2) CONSTRAINT [DF__Organizat__Invoi__5D21AF45] DEFAULT ((0)) NOT NULL,
    [InvoiceDueDays]                                   INT            NULL,
    [OrganizationAddress]                              VARCHAR (MAX)  NULL,
    [OrganizationCity]                                 VARCHAR (100)  NULL,
    [OrganizationState]                                VARCHAR (100)  NULL,
    [OrganizationZipcode]                              VARCHAR (10)   NULL,
    [MIF_Appendix]                                     VARCHAR (100)  NULL,
    [MIF_Description]                                  VARCHAR (500)  NULL,
    [MIF_Revision]                                     VARCHAR (100)  NULL,
    [AdminDatabaseName]                                VARCHAR (200)  NULL,
    [GoogleDriveRequestToken]                          VARCHAR (MAX)  NULL,
    [GoogleDriveAccessToken]                           VARCHAR (MAX)  NULL,
    [GoogleDriveRefreshToken]                          VARCHAR (MAX)  NULL,
    [GoogleDriveValidated]                             BIT            DEFAULT ((0)) NULL,
    [HHAXClientId]                                     NVARCHAR (MAX) NULL,
    [HHAXClientSecret]                                 NVARCHAR (MAX) NULL,
    [ShowInvoiceReadyRibbon]                           BIT            NULL,
    [Fax]                                              NVARCHAR (MAX) NULL,
    [FaxTwilioAccountSID]                              NVARCHAR (MAX) NULL,
    [FaxAuthToken]                                     NVARCHAR (MAX) NULL,
    [HasAggregator]                                    BIT            NULL,
    [TermsCondition]                                   NVARCHAR (MAX) NULL,
    [TermsConditionMobile]                             NVARCHAR (MAX) NULL,
    [SuperAdminUserName]                               NVARCHAR (100) DEFAULT ('me-admin') NULL,
    [ClaimMDAccountKey]                                NVARCHAR (MAX) NULL,
    [ClaimMDUserID]                                    NVARCHAR (MAX) NULL,
    [SandataBusinessEntityID]                          NVARCHAR (MAX) NULL,
    [SandataBusinessEntityMedicaidIdentifier]          NVARCHAR (MAX) NULL,
    [SandataUserID]                                    NVARCHAR (MAX) NULL,
    [SandataPassword]                                  NVARCHAR (MAX) NULL,
    [InvoiceAddressIsBilltoPayor]                      BIT            NULL,
    [InvoiceAddressIsIncludePatientAddress]            BIT            NULL,
    [InvoiceAddressIsIncludePatientAddressZip]         BIT            NULL,
    [InvoiceAddressIsIncludePatientAddressLine1]       BIT            NULL,
    [InvoiceAddressIsIncludePatientAddressLine2]       BIT            NULL,
    [InvoiceIsIncludePatientDOB]                       BIT            NULL,
    [UploadPath]                                       NVARCHAR (MAX) NULL, 
    [ToEmail]                                          NVARCHAR (MAX) NULL,
	[CC]                                               NVARCHAR (MAX) NULL,
	[Body]                                             NVARCHAR (MAX) NULL,
    [SandataIsProduction]                              BIT            DEFAULT ((0)) NULL,
    [ScheduleType] BIT NULL, 
    [EnforceAcrossAllClients] BIT NULL, 
    [EnvironmentType] BIT NOT NULL, 
    CONSTRAINT [PK__Organiza__CADB0B7236D01988] PRIMARY KEY CLUSTERED ([OrganizationID] ASC)
);
GO

