CREATE TABLE [dbo].[PayorEdi270Settings] (
    [PayorEdi270SettingId]                    BIGINT        NOT NULL,
    [ISA01_AuthorizationInformationQualifier] VARCHAR (2)   NULL,
    [ISA02_AuthorizationInformation]          VARCHAR (10)  NULL,
    [ISA03_SecurityInformationQualifier]      VARCHAR (2)   NULL,
    [ISA04_SecurityInformation]               VARCHAR (10)  NULL,
    [ISA05_InterchangeSenderIdQualifier]      VARCHAR (2)   NULL,
    [ISA06_InterchangeSenderId]               VARCHAR (15)  NULL,
    [ISA07_InterchangeReceiverIdQualifier]    VARCHAR (2)   NULL,
    [ISA08_InterchangeReceiverId]             VARCHAR (15)  NULL,
    [ISA09_InterchangeDate]                   VARCHAR (6)   NULL,
    [ISA10_InterchangeTime]                   VARCHAR (4)   NULL,
    [ISA11_RepetitionSeparator]               CHAR (1)      NULL,
    [ISA12_InterchangeControlVersionNumber]   VARCHAR (5)   NULL,
    [ISA13_InterchangeControlNumber]          BIGINT        NULL,
    [ISA13_UpdatedDate]                       DATETIME      NULL,
    [ISA14_AcknowledgementRequired]           VARCHAR (1)   NULL,
    [ISA15_UsageIndicator]                    CHAR (1)      NULL,
    [ISA16_ComponentElementSeparator]         CHAR (1)      NULL,
    [GS01_FunctionalIdentifierCode]           VARCHAR (2)   NULL,
    [GS02_ApplicationSenderCode]              VARCHAR (15)  NULL,
    [GS03_ApplicationReceiverCode]            VARCHAR (15)  NULL,
    [GS04_Date]                               VARCHAR (8)   NULL,
    [GS05_Time]                               VARCHAR (8)   NULL,
    [GS06_GroupControlNumber]                 VARCHAR (9)   NULL,
    [GS07_ResponsibleAgencyCode]              VARCHAR (2)   NULL,
    [GS08_VersionOrReleaseOrNo]               VARCHAR (12)  NULL,
    [ST01_TransactionSetIdentifier]           VARCHAR (3)   NULL,
    [ST02_TransactionSetControlNumber]        VARCHAR (9)   NULL,
    [ST03_ImplementationConventionReference]  VARCHAR (35)  NULL,
    [BHT01_HierarchicalStructureCode]         VARCHAR (4)   NULL,
    [BHT02_TransactionSetPurposeCode]         VARCHAR (2)   NULL,
    [BHT03_ReferenceIdentification]           VARCHAR (50)  NULL,
    [BHT04_Date]                              VARCHAR (50)  NULL,
    [BHT05_Time]                              VARCHAR (8)   NULL,
    [BHT06_TransactionTypeCode]               VARCHAR (2)   NULL,
    [SegmentTerminator]                       CHAR (1)      NULL,
    [ElementSeparator]                        CHAR (1)      NULL,
    [Source_HeirarchicalLevelCode]            VARCHAR (10)  NULL,
    [Source_EntityIdentifierCode]             VARCHAR (10)  NULL,
    [Source_EntityTypeQualifier]              VARCHAR (10)  NULL,
    [Source_NameLastOrOrganizationName]       VARCHAR (200) NULL,
    [Source_IdCodeQualifier]                  VARCHAR (10)  NULL,
    [Source_IdCodeQualifierEnum]              VARCHAR (50)  NULL,
    [Receiver_HeirarchicalLevelCode]          VARCHAR (10)  NULL,
    [Receiver_EntityIdentifierCode]           VARCHAR (10)  NULL,
    [Receiver_EntityTypeQualifier]            VARCHAR (10)  NULL,
    [Receiver_NameLastOrOrganizationName]     VARCHAR (200) NULL,
    [Receiver_IdCodeQualifier]                VARCHAR (10)  NULL,
    [Receiver_IdCodeQualifierEnum]            VARCHAR (50)  NULL,
    CONSTRAINT [PK_PayorEdi270Settings] PRIMARY KEY CLUSTERED ([PayorEdi270SettingId] ASC)
);

