CREATE TABLE [dbo].[ReferralBillingAuthorizations] (
    [ReferralBillingAuthorizationID]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [ReferralID]                      BIGINT         NOT NULL,
    [Type]                            NVARCHAR (20)  NULL,
    [AuthorizationCode]               NVARCHAR (20)  NULL,
    [StartDate]                       DATE           NULL,
    [EndDate]                         DATE           NULL,
    [IsDeleted]                       BIT            CONSTRAINT [DF_ReferralBillingAuthrizations_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedDate]                     DATETIME       NULL,
    [CreatedBy]                       BIGINT         NULL,
    [UpdatedDate]                     DATETIME       NULL,
    [UpdatedBy]                       BIGINT         NULL,
    [SystemID]                        VARCHAR (100)  NULL,
    [PayorID]                         BIGINT         NULL,
    [AllowedTime]                     BIGINT         NULL,
    [PriorAuthorizationFrequencyType] BIGINT         NULL,
    [AllowedTimeType]                 VARCHAR (100)  NULL,
    [ServiceCodeID]                   BIGINT         NULL,
    [Rate]                            FLOAT (53)     NULL,
    [RevenueCode]                     BIGINT         NULL,
    [UnitType]                        INT            NULL,
    [PerUnitQuantity]                 DECIMAL (18)   NULL,
    [RoundUpUnit]                     INT            NULL,
    [MaxUnit]                         INT            NULL,
    [DailyUnitLimit]                  INT            NULL,
    [CareType]                        BIGINT         NULL,
    [BillingUnitLimit]                INT            NULL,
    [ModifierID]                      BIGINT         NULL,
    [TaxonomyID]                      BIGINT         NULL,
    [AttachmentFileName]              NVARCHAR (MAX) NULL,
    [AttachmentFilePath]              NVARCHAR (MAX) NULL,
	[UnitLimitFrequency]			  INT            NULL,
    [DxCode] NVARCHAR(MAX) NULL, 
    [DxCodeID] NVARCHAR(MAX) NULL, 
    [PayRate]                         FLOAT (53)     NULL,
    [FacilityCode]                    NVARCHAR(MAX)  NULL, 
    CONSTRAINT [PK_ReferralBillingAuthrizations] PRIMARY KEY CLUSTERED ([ReferralBillingAuthorizationID] ASC)
);

