CREATE TABLE [dbo].[ReferralAssessmentReview] (
    [ReferralAssessmentID]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [ReferralID]                    BIGINT        NOT NULL,
    [Permanency]                    FLOAT (53)    NOT NULL,
    [DailyLiving]                   FLOAT (53)    NOT NULL,
    [SelfCare]                      FLOAT (53)    NOT NULL,
    [RelationshipsAndCommunication] FLOAT (53)    NOT NULL,
    [HousingAndMoneyManagement]     FLOAT (53)    NOT NULL,
    [WorkAndStudyLife]              FLOAT (53)    NOT NULL,
    [CareerAndEducationPlanning]    FLOAT (53)    NOT NULL,
    [LookingForward]                FLOAT (53)    NOT NULL,
    [AssessmentReview]              VARCHAR (MAX) NULL,
    [AssessmentDate]                DATE          NOT NULL,
    [CreatedDate]                   DATETIME      NOT NULL,
    [CreatedBy]                     BIGINT        NOT NULL,
    [UpdatedDate]                   DATETIME      NOT NULL,
    [UpdatedBy]                     BIGINT        NOT NULL,
    [SystemID]                      VARCHAR (50)  NULL,
    [Assignee]                      BIGINT        NULL,
    [MarkAsComplete]                BIT           DEFAULT ((0)) NOT NULL,
    [SignatureDate]                 DATETIME      NULL,
    [SignatureBy]                   BIGINT        NULL,
    [AssignedBy]                    BIGINT        NULL,
    [AssignedDate]                  DATETIME      NULL,
    [FileName]                      VARCHAR (100) NULL,
    [FilePath]                      VARCHAR (200) NULL,
    [IsDeleted]                     BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ReferralAssessmentReview] PRIMARY KEY CLUSTERED ([ReferralAssessmentID] ASC),
    CONSTRAINT [FK_ReferralAssessmentReview_Employees] FOREIGN KEY ([Assignee]) REFERENCES [dbo].[Employees] ([EmployeeID])
);

