CREATE TABLE [dbo].[Agencies] (
    [AgencyID]                 BIGINT        IDENTITY (1, 1) NOT NULL,
    [NickName]                 VARCHAR (50)  NULL,
    [ShortName]                VARCHAR (100) NULL,
    [CompanyName]              VARCHAR (50)  NULL,
    [RegionID]                 BIGINT        NULL,
    [TaxID]                    VARCHAR (50)  NULL,
    [IsTribe]                  BIT           NULL,
    [AgencyTypeID]             BIGINT        NULL,
    [BillingGroupID]           BIGINT        NULL,
    [ContactTitle]             VARCHAR (50)  NULL,
    [ContactName]              VARCHAR (50)  NULL,
    [ContactHomePageUrl]       VARCHAR (100) NULL,
    [Email]                    VARCHAR (50)  NULL,
    [Phone]                    VARCHAR (15)  NULL,
    [Fax]                      VARCHAR (15)  NULL,
    [Address]                  VARCHAR (100) NULL,
    [City]                     VARCHAR (50)  NULL,
    [StateCode]                VARCHAR (10)  NULL,
    [ZipCode]                  VARCHAR (15)  NULL,
    [Notes]                    VARCHAR (500) NULL,
    [FiscalStartYear]          DATE          NULL,
    [FiscalEndYear]            DATE          NULL,
    [RespiteHours]             INT           NULL,
    [AgencyPrefix]             VARCHAR (2)   NULL,
    [InsuranceCompanyName]     VARCHAR (100) NULL,
    [InsuranceCompanyAddress1] VARCHAR (100) NULL,
    [InsuranceCompanyAddress2] VARCHAR (100) NULL,
    [InsuranceCompanyCSZ]      VARCHAR (100) NULL,
    [InsuranceTypeID]          BIGINT        NULL,
    [IsUseCortexForBilling]    BIT           NULL,
    [IsMultipleLocation]       BIT           NULL,
    [IsUsesAuthorization]      BIT           NULL,
    [IsDeleted]                BIT           CONSTRAINT [DF_Agencies_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedDate]              DATETIME      NULL,
    [CreatedBy]                BIGINT        NULL,
    [UpdatedDate]              DATETIME      NULL,
    [UpdatedBy]                BIGINT        NULL,
    [SystemID]                 VARCHAR (100) NULL,
    [AgencyType]               VARCHAR (100) NOT NULL,
    [TIN]                      VARCHAR (100) NULL,
    [EIN]                      VARCHAR (100) NULL,
    [Mobile]                   VARCHAR (15)  NULL,
    CONSTRAINT [PK_Agencies] PRIMARY KEY CLUSTERED ([AgencyID] ASC),
    CONSTRAINT [FK_Agencies_AgencyTypes] FOREIGN KEY ([AgencyTypeID]) REFERENCES [dbo].[AgencyTypes] ([AgencyTypeID]),
    CONSTRAINT [FK_Agencies_BillingGroups] FOREIGN KEY ([BillingGroupID]) REFERENCES [dbo].[BillingGroups] ([BillingGroupID]),
    CONSTRAINT [FK_Agencies_InsuranceTypes] FOREIGN KEY ([InsuranceTypeID]) REFERENCES [dbo].[InsuranceTypes] ([InsuranceTypeID]),
    CONSTRAINT [FK_Agencies_Regions] FOREIGN KEY ([RegionID]) REFERENCES [dbo].[Regions] ([RegionID])
);

