CREATE TABLE [dbo].[CareForms] (
    [CareFormID]                         BIGINT         IDENTITY (1, 1) NOT NULL,
    [ReferralID]                         BIGINT         NULL,
    [CareFormDate]                       DATETIME       NULL,
    [LocationOfService]                  NVARCHAR (MAX) NULL,
    [Phone]                              NVARCHAR (20)  NULL,
    [Cell]                               NVARCHAR (20)  NULL,
    [Email]                              NVARCHAR (300) NULL,
    [PSI_StartDate]                      DATETIME       NULL,
    [PSI_ENDDate]                        DATETIME       NULL,
    [ServiceRequested]                   VARCHAR (MAX)  NULL,
    [IsMedicallyFrail]                   BIT            NULL,
    [SpecificFunctionalLimitations]      NVARCHAR (MAX) NULL,
    [IsChargesForServicesRendered]       INT            NULL,
    [OnRequest]                          BIT            NULL,
    [PlanOfSupervision]                  NVARCHAR (MAX) NULL,
    [DurationOfServices]                 NVARCHAR (MAX) NULL,
    [StatementsOfGoals]                  NVARCHAR (MAX) NULL,
    [ObjectivesOfServices]               NVARCHAR (MAX) NULL,
    [DischargePlans]                     NVARCHAR (MAX) NULL,
    [DescriptionHowTheTasksArePerformed] NVARCHAR (MAX) NULL,
    [PertinentDiagnosis]                 NVARCHAR (MAX) NULL,
    [IsAttachedMedicationForm]           BIT            NULL,
    [Medications]                        NVARCHAR (MAX) NULL,
    [Treatments]                         NVARCHAR (MAX) NULL,
    [EquipmentNeeds]                     NVARCHAR (MAX) NULL,
    [Diet]                               NVARCHAR (MAX) NULL,
    [NutritionalNeeds]                   NVARCHAR (MAX) NULL,
    [IsPhysiciansOrdersNeeded]           BIT            NULL,
    [PhysicianOrdersDescription]         NVARCHAR (MAX) NULL,
    [ClientSignature]                    NVARCHAR (MAX) NULL,
    [ClientSignatureDate]                DATETIME       NULL,
    [NurseSignature]                     NVARCHAR (MAX) NULL,
    [NurseSignatureDate]                 DATETIME       NULL,
    [CreatedDate]                        DATETIME       NULL,
    [CreatedBy]                          BIGINT         NULL,
    [UpdatedDate]                        DATETIME       NULL,
    [UpdatedBy]                          BIGINT         NULL,
    [SystemID]                           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CareForm] PRIMARY KEY CLUSTERED ([CareFormID] ASC),
    CONSTRAINT [FK_CareForm_Referrals] FOREIGN KEY ([ReferralID]) REFERENCES [dbo].[Referrals] ([ReferralID])
);

