CREATE TABLE [dbo].[JO_Referrals] (
    [JO_ReferralID]                   BIGINT        IDENTITY (1, 1) NOT NULL,
    [ReferralID]                      BIGINT        NOT NULL,
    [Title]                           VARCHAR (10)  NULL,
    [FirstName]                       VARCHAR (50)  NULL,
    [MiddleName]                      VARCHAR (50)  NULL,
    [LastName]                        VARCHAR (50)  NULL,
    [Dob]                             DATE          NULL,
    [Gender]                          CHAR (1)      NULL,
    [RecordRequestEmail]              VARCHAR (MAX) NULL,
    [LanguageID]                      BIGINT        NULL,
    [ClientNumber]                    VARCHAR (15)  NULL,
    [AHCCCSID]                        VARCHAR (10)  NULL,
    [CISNumber]                       VARCHAR (15)  COLLATE Latin1_General_CI_AI NULL,
    [Population]                      VARCHAR (50)  NULL,
    [HealthPlan]                      VARCHAR (500) NULL,
    [RateCode]                        VARCHAR (100) NULL,
    [RateCodeStartDate]               DATE          NULL,
    [RateCodeEndDate]                 DATE          NULL,
    [AHCCCSEnrollDate]                DATE          NULL,
    [PlacementRequirement]            VARCHAR (MAX) NULL,
    [BehavioralIssue]                 VARCHAR (MAX) NULL,
    [OtherInformation]                VARCHAR (MAX) NULL,
    [AgencyID]                        BIGINT        NULL,
    [AgencyLocationID]                BIGINT        NULL,
    [CaseManagerID]                   BIGINT        NULL,
    [FirstDOS]                        DATE          NULL,
    [ReferralDate]                    DATE          NULL,
    [ClosureDate]                     DATE          NULL,
    [ClosureReason]                   VARCHAR (500) NULL,
    [CareConsent]                     BIT           NULL,
    [SelfAdministrationofMedication]  BIT           NULL,
    [HealthInformationDisclosure]     BIT           NULL,
    [AdmissionRequirements]           BIT           NULL,
    [AdmissionOrientation]            BIT           NULL,
    [ZarephathCrisisPlan]             VARCHAR (2)   NULL,
    [NetworkCrisisPlan]               VARCHAR (5)   NULL,
    [NCPExpirationDate]               DATETIME      NULL,
    [PermissionForVoiceMail]          BIT           NULL,
    [PermissionForEmail]              BIT           NULL,
    [PermissionForSMS]                BIT           NULL,
    [PermissionForMail]               BIT           CONSTRAINT [DF_JO_Referrals_PermissionForMail] DEFAULT ((0)) NULL,
    [AROI]                            VARCHAR (5)   NULL,
    [AROIAgencyID]                    BIGINT        NULL,
    [AROIExpirationDate]              DATE          NULL,
    [PHI]                             BIT           NULL,
    [PHIAgencyID]                     BIGINT        NULL,
    [PHIExpirationDate]               DATE          NULL,
    [RespiteService]                  BIT           NULL,
    [ZSPRespite]                      BIT           NULL,
    [ZSPRespiteExpirationDate]        DATE          NULL,
    [ZSPRespiteGuardianSignature]     BIT           NULL,
    [ZSPRespiteBHPSigned]             BIT           NULL,
    [LifeSkillsService]               BIT           NULL,
    [ZSPLifeSkills]                   BIT           NULL,
    [ZSPLifeSkillsExpirationDate]     DATE          NULL,
    [ZSPLifeSkillsGuardianSignature]  BIT           NULL,
    [ZSPLifeSkillsBHPSigned]          BIT           NULL,
    [CounselingService]               BIT           NULL,
    [ZSPCounselling]                  BIT           NULL,
    [ZSPCounsellingExpirationDate]    DATE          NULL,
    [ZSPCounsellingGuardianSignature] BIT           NULL,
    [ZSPCounsellingBHPSigned]         BIT           NULL,
    [NetworkServicePlan]              BIT           NULL,
    [NSPExpirationDate]               DATE          NULL,
    [NSPGuardianSignature]            BIT           NULL,
    [NSPBHPSigned]                    BIT           NULL,
    [NSPSPidentifyService]            VARCHAR (2)   NULL,
    [BXAssessment]                    BIT           NULL,
    [BXAssessmentExpirationDate]      DATE          NULL,
    [BXAssessmentBHPSigned]           BIT           NULL,
    [Demographic]                     VARCHAR (5)   NULL,
    [DemographicExpirationDate]       DATE          NULL,
    [SNCD]                            VARCHAR (5)   NULL,
    [SNCDExpirationDate]              DATE          NULL,
    [ACAssessment]                    BIT           NULL,
    [ACAssessmentExpirationDate]      DATE          NULL,
    [IsCheckListCompleted]            BIT           NULL,
    [IsSparFormCompleted]             BIT           NULL,
    [IsSaveAsDraft]                   BIT           CONSTRAINT [DF_JO_Referrals_IsSaveAsDraft] DEFAULT ((0)) NULL,
    [ReferralStatusID]                BIGINT        NULL,
    [Assignee]                        BIGINT        NULL,
    [DropOffLocation]                 BIGINT        NULL,
    [PickUpLocation]                  BIGINT        NULL,
    [NeedPrivateRoom]                 BIT           NULL,
    [OrientationDate]                 DATE          NULL,
    [FrequencyCodeID]                 BIGINT        NULL,
    [ClientID]                        BIGINT        NULL,
    [CreatedDate]                     DATETIME      NOT NULL,
    [CreatedBy]                       BIGINT        NOT NULL,
    [UpdatedDate]                     DATETIME      NOT NULL,
    [UpdatedBy]                       BIGINT        NOT NULL,
    [SystemID]                        VARCHAR (100) NOT NULL,
    [IsDeleted]                       BIT           CONSTRAINT [DF_JO_Referrals_IsDeleted] DEFAULT ((0)) NULL,
    [RegionID]                        BIGINT        NULL,
    [NotifyCaseManager]               BIT           CONSTRAINT [DF_JO_Referrals_NotifyCaseManager] DEFAULT ((0)) NULL,
    [ReferralSourceID]                INT           NULL,
    [LastAttendedDate]                DATE          NULL,
    [Action]                          CHAR (1)      NOT NULL,
    [ActionDate]                      DATETIME      NOT NULL,
    [ClientNickName]                  VARCHAR (100) NULL,
    [ScheduleRequestDates]            VARCHAR (500) NULL,
    CONSTRAINT [PK_JO_Referrals] PRIMARY KEY CLUSTERED ([JO_ReferralID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_JO_Referrals_ReferralStatusID_ActionDate_DBCAE]
    ON [dbo].[JO_Referrals]([ReferralStatusID] ASC, [ActionDate] ASC)
    INCLUDE([ReferralID]);

