CREATE TABLE [dbo].[PayorEdi837Settings] (
    [PayorEdi837SettingId]                                               BIGINT        IDENTITY (1, 1) NOT NULL,
    [PayorID]                                                            BIGINT        NOT NULL,
    [ISA01_AuthorizationInformationQualifier]                            VARCHAR (2)   NULL,
    [ISA02_AuthorizationInformation]                                     VARCHAR (10)  NULL,
    [ISA03_SecurityInformationQualifier]                                 VARCHAR (2)   NULL,
    [ISA04_SecurityInformation]                                          VARCHAR (10)  NULL,
    [ISA05_InterchangeSenderIdQualifier]                                 VARCHAR (2)   NULL,
    [ISA06_InterchangeSenderId]                                          VARCHAR (15)  NULL,
    [ISA07_InterchangeReceiverIdQualifier]                               VARCHAR (2)   NULL,
    [ISA08_InterchangeReceiverId]                                        VARCHAR (15)  NULL,
    [ISA09_InterchangeDate]                                              VARCHAR (6)   NULL,
    [ISA10_InterchangeTime]                                              VARCHAR (4)   NULL,
    [ISA11_RepetitionSeparator]                                          CHAR (1)      NULL,
    [ISA12_InterchangeControlVersionNumber]                              VARCHAR (5)   NULL,
    [ISA13_InterchangeControlNumber]                                     VARCHAR (9)   NULL,
    [ISA14_AcknowledgementRequired]                                      VARCHAR (1)   NULL,
    [ISA15_UsageIndicator]                                               CHAR (1)      NULL,
    [ISA16_ComponentElementSeparator]                                    CHAR (1)      NULL,
    [GS01_FunctionalIdentifierCode]                                      VARCHAR (2)   NULL,
    [GS02_ApplicationSenderCode]                                         VARCHAR (15)  NULL,
    [GS03_ApplicationReceiverCode]                                       VARCHAR (15)  NULL,
    [GS04_Date]                                                          VARCHAR (8)   NULL,
    [GS05_Time]                                                          VARCHAR (8)   NULL,
    [GS06_GroupControlNumber]                                            VARCHAR (9)   NULL,
    [GS07_ResponsibleAgencyCode]                                         VARCHAR (2)   NULL,
    [GS08_VersionOrReleaseOrNo]                                          VARCHAR (12)  NULL,
    [ST01_TransactionSetIdentifier]                                      VARCHAR (3)   NULL,
    [ST02_TransactionSetControlNumber]                                   VARCHAR (9)   NULL,
    [ST03_ImplementationConventionReference]                             VARCHAR (35)  NULL,
    [BHT01_HierarchicalStructureCode]                                    VARCHAR (4)   NULL,
    [BHT02_TransactionSetPurposeCode]                                    VARCHAR (2)   NULL,
    [BHT03_ReferenceIdentification]                                      VARCHAR (50)  NULL,
    [BHT04_Date]                                                         VARCHAR (50)  NULL,
    [BHT05_Time]                                                         VARCHAR (8)   NULL,
    [BHT06_TransactionTypeCode]                                          VARCHAR (2)   NULL,
    [Submitter_NM101_EntityIdentifierCodeEnum]                           VARCHAR (3)   NULL,
    [Submitter_NM102_EntityTypeQualifier]                                CHAR (1)      NULL,
    [Submitter_NM103_NameLastOrOrganizationName]                         VARCHAR (60)  NULL,
    [Submitter_NM104_NameFirst]                                          VARCHAR (35)  NULL,
    [Submitter_NM105_NameMiddle]                                         VARCHAR (25)  NULL,
    [Submitter_NM106_NamePrefix]                                         VARCHAR (10)  NULL,
    [Submitter_NM107_NameSuffix]                                         VARCHAR (10)  NULL,
    [Submitter_NM108_IdCodeQualifier]                                    VARCHAR (2)   NULL,
    [Submitter_NM109_IdCodeQualifierEnum]                                VARCHAR (80)  NULL,
    [Submitter_NM110_EntityRelationshipCode]                             VARCHAR (2)   NULL,
    [Submitter_NM111_EntityIdentifierCode]                               VARCHAR (3)   NULL,
    [Submitter_NM112_NameLastOrOrganizationName]                         VARCHAR (60)  NULL,
    [Submitter_EDIContact1_PER01_ContactFunctionCode]                    VARCHAR (2)   NULL,
    [Submitter_EDIContact1_PER02_Name]                                   VARCHAR (60)  NULL,
    [Submitter_EDIContact1_PER03_CommunicationNumberQualifier]           VARCHAR (2)   NULL,
    [Submitter_EDIContact1_PER04_CommunicationNumber]                    VARCHAR (256) NULL,
    [Submitter_EDIContact1_PER05_CommunicationNumberQualifier]           VARCHAR (2)   NULL,
    [Submitter_EDIContact1_PER06_CommunicationNumber]                    VARCHAR (256) NULL,
    [Submitter_EDIContact1_PER07_CommunicationNumberQualifier]           VARCHAR (2)   NULL,
    [Submitter_EDIContact1_PER08_CommunicationNumber]                    VARCHAR (256) NULL,
    [Submitter_EDIContact1_PER09_ContactInquiryReference]                VARCHAR (20)  NULL,
    [Submitter_EDIContact2_PER01_ContactFunctionCode]                    VARCHAR (2)   NULL,
    [Submitter_EDIContact2_PER02_Name]                                   VARCHAR (60)  NULL,
    [Submitter_EDIContact2_PER03_CommunicationNumberQualifier]           VARCHAR (2)   NULL,
    [Submitter_EDIContact2_PER04_CommunicationNumber]                    VARCHAR (256) NULL,
    [Submitter_EDIContact2_PER05_CommunicationNumberQualifier]           VARCHAR (2)   NULL,
    [Submitter_EDIContact2_PER06_CommunicationNumber]                    VARCHAR (256) NULL,
    [Submitter_EDIContact2_PER07_CommunicationNumberQualifier]           VARCHAR (2)   NULL,
    [Submitter_EDIContact2_PER08_CommunicationNumber]                    VARCHAR (256) NULL,
    [Submitter_EDIContact2_PER09_ContactInquiryReference]                VARCHAR (20)  NULL,
    [Receiver_NM101_EntityIdentifierCodeEnum]                            VARCHAR (3)   NULL,
    [Receiver_NM102_EntityTypeQualifier]                                 CHAR (1)      NULL,
    [Receiver_NM103_NameLastOrOrganizationName]                          VARCHAR (60)  NULL,
    [Receiver_NM104_NameFirst]                                           VARCHAR (35)  NULL,
    [Receiver_NM105_NameMiddle]                                          VARCHAR (25)  NULL,
    [Receiver_NM106_NamePrefix]                                          VARCHAR (10)  NULL,
    [Receiver_NM107_NameSuffix]                                          VARCHAR (10)  NULL,
    [Receiver_NM108_IdCodeQualifier]                                     VARCHAR (2)   NULL,
    [Receiver_NM109_IdCodeQualifierEnum]                                 VARCHAR (80)  NULL,
    [Receiver_NM110_EntityRelationshipCode]                              VARCHAR (2)   NULL,
    [Receiver_NM111_EntityIdentifierCode]                                VARCHAR (3)   NULL,
    [Receiver_NM112_NameLastOrOrganizationName]                          VARCHAR (60)  NULL,
    [SE01_NumberOfIncludedSegments]                                      VARCHAR (10)  NULL,
    [SE02_TransactionSetControlNumber]                                   VARCHAR (9)   NULL,
    [GE01_NumberOfTransactionSetsIncluded]                               VARCHAR (6)   NULL,
    [GE02_GroupControlNumber]                                            VARCHAR (9)   NULL,
    [IEA01_NumberOfIncludedFunctionalGroups]                             VARCHAR (5)   NULL,
    [IEA02_InterchangeControlNumber]                                     VARCHAR (9)   NULL,
    [BillingProvider_HL01_HierarchicalIDNumber]                          VARCHAR (12)  NULL,
    [BillingProvider_HL02_HierarchicalParentIDNumber]                    VARCHAR (12)  NULL,
    [BillingProvider_HL03_HierarchicalLevelCode]                         VARCHAR (2)   NULL,
    [BillingProvider_HL04_HierarchicalChildCode]                         VARCHAR (1)   NULL,
    [BillingProvider_NM101_EntityIdentifierCode]                         VARCHAR (3)   NULL,
    [BillingProvider_NM102_EntityTypeQualifier]                          VARCHAR (1)   NULL,
    [BillingProvider_NM108_IdentificationCodeQualifier]                  VARCHAR (2)   NULL,
    [BillingProvider_REF01_ReferenceIdentificationQualifier]             VARCHAR (3)   NULL,
    [Subscriber_HL02_HierarchicalParentIDNumber]                         VARCHAR (12)  NULL,
    [Subscriber_HL03_HierarchicalLevelCode]                              VARCHAR (2)   NULL,
    [Subscriber_HL04_HierarchicalChildCode]                              VARCHAR (1)   NULL,
    [Subscriber_SBR01_PayerResponsibilitySequenceNumberCode]             VARCHAR (1)   NULL,
    [Subscriber_SBR02_RelationshipCode]                                  VARCHAR (2)   NULL,
    [Subscriber_SBR09_ClaimFilingIndicatorCode]                          VARCHAR (2)   NULL,
    [Subscriber_NM101_EntityIdentifierCode]                              VARCHAR (3)   NULL,
    [Subscriber_NM102_EntityIdentifierCode]                              VARCHAR (1)   NULL,
    [Subscriber_NM108_IdentificationCodeQualifier]                       VARCHAR (2)   NULL,
    [Subscriber_NM109_SubscriberPrimaryIdentifier]                       VARCHAR (80)  NULL,
    [Subscriber_DMG01_DateTimePeriodFormatQualifier]                     VARCHAR (3)   NULL,
    [Subscriber_Payer_NM101_EntityIdentifierCode]                        VARCHAR (3)   NULL,
    [Subscriber_Payer_NM102_EntityTypeQualifier]                         VARCHAR (1)   NULL,
    [Subscriber_Payer_NM108_IdentificationCodeQualifier]                 VARCHAR (2)   NULL,
    [Subscriber_Payer_NM109_IdentificationCode]                          VARCHAR (80)  NULL,
    [Claim_CLM01_PatientAccountNumber]                                   VARCHAR (20)  NULL,
    [Claim_CLM05_02_FacilityCodeQualifier]                               VARCHAR (2)   NULL,
    [Claim_CLM05_03_ClaimFrequencyCode]                                  VARCHAR (1)   NULL,
    [Claim_CLM06_ProviderSignatureOnFile]                                VARCHAR (1)   NULL,
    [Claim_CLM07_ProviderAcceptAssignment]                               VARCHAR (1)   NULL,
    [Claim_CLM08_AssignmentOfBenefitsIndicator]                          VARCHAR (1)   NULL,
    [Claim_CLM09_ReleaseOfInformationCode]                               VARCHAR (1)   NULL,
    [Claim_CLM010_PatientSignatureSource]                                VARCHAR (1)   NULL,
    [Claim_REF01_ReferenceIdentificationQualifier]                       VARCHAR (3)   NULL,
    [Claim_REF02_MedicalRecordNumber]                                    VARCHAR (50)  NULL,
    [Claim_HI01_01_PrincipalDiagnosisQualifier]                          VARCHAR (3)   NULL,
    [Claim_RenderringProvider_NM01_EntityIdentifierCode]                 VARCHAR (3)   NULL,
    [Claim_RenderringProvider_NM02_EntityTypeQualifier]                  VARCHAR (1)   NULL,
    [Claim_RenderringProvider_NM108_IdentificationCodeQualifier]         VARCHAR (2)   NULL,
    [Claim_ServiceFacility_NM101_EntityIdentifierCode]                   VARCHAR (2)   NULL,
    [Claim_ServiceFacility_NM102_EntityTypeQualifier]                    VARCHAR (1)   NULL,
    [Claim_ServiceFacility_NM108_IdentificationCodeQualifier]            VARCHAR (2)   NULL,
    [Claim_ServiecLine_LX01_AssignedNumber]                              VARCHAR (6)   NULL,
    [Claim_ServiecLine_SV101_01_ProductServiceIDQualifier]               VARCHAR (2)   NULL,
    [Claim_ServiecLine_SV103_BasisOfMeasurement]                         VARCHAR (2)   NULL,
    [Claim_ServiceLine_SV107_01_DiagnosisCodePointer]                    VARCHAR (50)  NULL,
    [Claim_ServiceLine_Date_DTP01_DateTimeQualifier]                     VARCHAR (3)   NULL,
    [Claim_ServiceLine_Date_DTP02_DateTimePeriodFormatQualifier]         VARCHAR (3)   NULL,
    [Claim_ServiceLine_Ref_REF01_ReferenceIdentificationQualifier]       VARCHAR (3)   NULL,
    [Claim_ServiceLine_Ref_REF02_ReferenceIdentification]                VARCHAR (50)  NULL,
    [SegmentTerminator]                                                  CHAR (1)      NULL,
    [ElementSeparator]                                                   CHAR (1)      NULL,
    [SkipSituationalContent]                                             BIT           CONSTRAINT [DF_PayorEdi837Settings_SkipSituationalContent] DEFAULT ((0)) NOT NULL,
    [ISA13_InterchangeControlNo]                                         VARCHAR (9)   NULL,
    [ISA13_UpdatedDate]                                                  DATETIME      NULL,
    [RequiredRenderingProvider]                                          BIT           CONSTRAINT [DF__PayorEdi8__Requi__4119A21D] DEFAULT ((0)) NOT NULL,
    [Claim_CLM05_03_ClaimFrequencyCode_Replcement]                       VARCHAR (1)   NULL,
    [Claim_CLM05_03_ClaimFrequencyCode_Void]                             VARCHAR (1)   NULL,
    [Claim_ServiceLine_Ref_REF01_ReferenceIdentificationQualifier_F8_02] VARCHAR (3)   NULL,
    [Claim_ServiceLine_Ref_REF02_ReferenceIdentification_F8_02]          VARCHAR (50)  NULL,
    [CheckForPolicyNumber]                                               BIT           CONSTRAINT [DF__PayorEdi8__Check__2724C5F0] DEFAULT ((0)) NOT NULL,
    [CMS1500HourRounding]                                                INT           NULL,
    [UB04HourRounding]                                                   INT           NULL,
    [BillingProvider_PRV01_ProviderCode]                                 VARCHAR (3)   NULL,
    [BillingProvider_PRV02_ReferenceIdentificationQualifier]             VARCHAR (3)   NULL,
    [BillingProvider_PRV03_ProviderTaxonomyCode]                         VARCHAR (50)  NULL,
    [Claim_Prior_REF01_ReferenceIdentificationQualifier]                 VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__Claim__1486F2C8] DEFAULT ('G1') NULL,
    [ReferringProvider_NM101_EntityIdentifierCode]                       VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__Refer__157B1701] DEFAULT ('DN') NULL,
    [ReferringProvider_NM102_EntityTypeQualifier]                        VARCHAR (1)   NULL,
    [ReferringProvider_NM108_IDCodeQualifier]                            VARCHAR (2)   CONSTRAINT [DF__PayorEdi8__Refer__17635F73] DEFAULT ('XX') NULL,
    [RenderingProvider_NM101_EntityIdentifierCode]                       VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__Rende__185783AC] DEFAULT ('82') NULL,
    [RenderingProvider_NM102_EntityTypeQualifier]                        VARCHAR (1)   NULL,
    [RenderingProvider_NM108_IDCodeQualifier]                            VARCHAR (2)   CONSTRAINT [DF__PayorEdi8__Rende__1A3FCC1E] DEFAULT ('XX') NULL,
    [RenderingProvider_PRV01_ProviderCode]                               VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__Rende__1B33F057] DEFAULT ('PE') NULL,
    [RenderingProvider_PRV02_ReferenceIdentificationQualifier]           VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__Rende__1C281490] DEFAULT ('PXC') NULL,
    [I_GS08_ST03_VersionOrReleaseOrNo]                                   VARCHAR (12)  CONSTRAINT [DF__PayorEdi8__I_GS0__1D1C38C9] DEFAULT ('005010X223A2') NULL,
    [I_PVR03_ReferenceIdentification]                                    VARCHAR (50)  CONSTRAINT [DF__PayorEdi8__I_PVR__1E105D02] DEFAULT ('251E00000X') NULL,
    [I_AttendingProvider_NM101_EntityIdentifierCode]                     VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__I_Att__1F04813B] DEFAULT ('71') NULL,
    [I_AttendingProvider_NM102_EntityTypeQualifier]                      VARCHAR (1)   CONSTRAINT [DF__PayorEdi8__I_Att__1FF8A574] DEFAULT ('1') NULL,
    [I_AttendingProvider_NM108_IDCodeQualifier]                          VARCHAR (2)   CONSTRAINT [DF__PayorEdi8__I_Att__20ECC9AD] DEFAULT ('XX') NULL,
    [I_Claim_DTP01_01_DateTimeQualifier]                                 VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__I_Cla__21E0EDE6] DEFAULT ('434') NULL,
    [I_Claim_DTP01_02_DateTimePeriodFormatQualifier]                     VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__I_Cla__22D5121F] DEFAULT ('RD8') NULL,
    [I_Claim_DTP02_01_DateTimeQualifier]                                 VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__I_Cla__23C93658] DEFAULT ('435') NULL,
    [I_Claim_DTP02_02_DateTimePeriodFormatQualifier]                     VARCHAR (3)   CONSTRAINT [DF__PayorEdi8__I_Cla__24BD5A91] DEFAULT ('DT') NULL,
    CONSTRAINT [PK_PayerEdi837Settings] PRIMARY KEY CLUSTERED ([PayorEdi837SettingId] ASC)
);

