CREATE TABLE [dbo].[ReferralOutcomeMeasurements] (
    [ReferralOutcomeMeasurementID] BIGINT        IDENTITY (1, 1) NOT NULL,
    [ReferralID]                   BIGINT        NOT NULL,
    [WorkCommunity]                INT           NULL,
    [ScheduledAppointment]         INT           NULL,
    [AskForHelp]                   INT           NULL,
    [CommunicateEffectively]       INT           NULL,
    [PositiveBehavior]             INT           NULL,
    [QualityFriendship]            INT           NULL,
    [RespectOther]                 INT           NULL,
    [StickUp]                      INT           NULL,
    [LifeSkillGoals]               INT           NULL,
    [StayOutOfTrouble]             INT           NULL,
    [StayOutOfTroubleText]         VARCHAR (200) NULL,
    [SuccessfulInSchool]           INT           NULL,
    [SuccessfulInSchoolText]       VARCHAR (200) NULL,
    [SuccessfulInLiving]           INT           NULL,
    [SuccessfulInLivingText]       VARCHAR (200) NULL,
    [AdulthoodNeeds]               INT           NULL,
    [AdulthoodNeedText]            VARCHAR (200) NULL,
    [CreatedDate]                  DATETIME      NOT NULL,
    [OutcomeMeasurementDate]       DATE          NOT NULL,
    [CreatedBy]                    BIGINT        NOT NULL,
    [UpdatedDate]                  DATETIME      NOT NULL,
    [UpdatedBy]                    BIGINT        NOT NULL,
    [SystemID]                     VARCHAR (100) NULL,
    [IsDeleted]                    BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ReferralOutcomeMeasurements] PRIMARY KEY CLUSTERED ([ReferralOutcomeMeasurementID] ASC)
);

