CREATE TABLE [dbo].[ReferralMonthlySummaries] (
    [ReferralMonthlySummariesID]        BIGINT        IDENTITY (1, 1) NOT NULL,
    [ReferralID]                        BIGINT        NOT NULL,
    [Medication]                        BIT           NULL,
    [Breakfast]                         VARCHAR (MAX) NULL,
    [BreakfastTxt]                      VARCHAR (MAX) NULL,
    [Lunch]                             VARCHAR (MAX) NULL,
    [LunchTxt]                          VARCHAR (MAX) NULL,
    [Dinner]                            VARCHAR (MAX) NULL,
    [DinnerTxt]                         VARCHAR (MAX) NULL,
    [MoodforThroughoutWeekend]          VARCHAR (MAX) NULL,
    [MoodforThroughoutWeekendTxt]       VARCHAR (MAX) NULL,
    [OutingDetails]                     VARCHAR (MAX) NULL,
    [PCIInformation]                    VARCHAR (MAX) NULL,
    [TreatmentPlan]                     VARCHAR (MAX) NULL,
    [MedicationsDispensed]              BIT           NULL,
    [MedicationsDispensedTxt]           VARCHAR (MAX) NULL,
    [Nextvisit]                         VARCHAR (MAX) NULL,
    [CurrentServicePlan]                BIT           NULL,
    [BelongingsandMedicationsReturned]  BIT           NULL,
    [CoordinationofCareatPickup]        VARCHAR (MAX) NULL,
    [CoordinationofCareatPickupOption]  VARCHAR (MAX) NULL,
    [CoordinationofCareatPickupTxt]     VARCHAR (MAX) NULL,
    [CoordinationofCareatDropOff]       VARCHAR (MAX) NULL,
    [CoordinationofCareatDropOffOption] VARCHAR (MAX) NULL,
    [CoordinationofCareatDropOffTxt]    VARCHAR (MAX) NULL,
    [MonthlySummaryStartDate]           DATETIME      NULL,
    [MonthlySummaryEndDate]             DATETIME      NULL,
    [CreatedBy]                         BIGINT        NOT NULL,
    [UpdatedBy]                         BIGINT        NOT NULL,
    [CreatedDate]                       DATETIME      NOT NULL,
    [UpdatedDate]                       DATETIME      NOT NULL,
    [SystemID]                          VARCHAR (30)  NOT NULL,
    [FacilityID]                        BIGINT        NULL,
    [IsDeleted]                         BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ReferralMonthlySummaries] PRIMARY KEY CLUSTERED ([ReferralMonthlySummariesID] ASC),
    CONSTRAINT [FK_ReferralMonthlySummaries_Facilities] FOREIGN KEY ([FacilityID]) REFERENCES [dbo].[Facilities] ([FacilityID]),
    CONSTRAINT [FK_ReferralMonthlySummaries_Referrals] FOREIGN KEY ([ReferralID]) REFERENCES [dbo].[Referrals] ([ReferralID])
);

