CREATE TABLE [dbo].[DemoReferrals] (
    [Status]                           NVARCHAR (255) NULL,
    [First Name]                       NVARCHAR (255) NULL,
    [Middle Name]                      NVARCHAR (255) NULL,
    [Last Name]                        NVARCHAR (255) NULL,
    [Nickname]                         NVARCHAR (255) NULL,
    [DOB]                              DATETIME       NULL,
    [Gender]                           NVARCHAR (255) NULL,
    [AHCCCS ID]                        NVARCHAR (255) NULL,
    [AHCCCS Verification]              DATETIME       NULL,
    [CIS #]                            FLOAT (53)     NULL,
    [Population]                       NVARCHAR (255) NULL,
    [Health Plan]                      NVARCHAR (255) NULL,
    [Title]                            NVARCHAR (255) NULL,
    [Records Req]                      NVARCHAR (255) NULL,
    [Rate Code]                        FLOAT (53)     NULL,
    [R#C# Start]                       NVARCHAR (255) NULL,
    [R#C# End]                         NVARCHAR (255) NULL,
    [Region]                           NVARCHAR (255) NULL,
    [Language]                         NVARCHAR (255) NULL,
    [Assignee]                         NVARCHAR (255) NULL,
    [Orientation Date]                 NVARCHAR (255) NULL,
    [Drop off Location]                NVARCHAR (255) NULL,
    [Pick Up Location]                 NVARCHAR (255) NULL,
    [Frequency Code]                   NVARCHAR (255) NULL,
    [Need Private Room]                NVARCHAR (255) NULL,
    [Placement Requirements]           NVARCHAR (255) NULL,
    [Behavioral Issue]                 NVARCHAR (255) NULL,
    [ISPrimaryPlacementLegalGuardian ] NVARCHAR (255) NULL,
    [ISDCSLegal]                       NVARCHAR (255) NULL,
    [Contact Type]                     NVARCHAR (255) NULL,
    [ROI Type]                         NVARCHAR (255) NULL,
    [ROI Expire]                       NVARCHAR (255) NULL,
    [Contact First]                    NVARCHAR (255) NULL,
    [Contact Last]                     NVARCHAR (255) NULL,
    [Contact Email]                    NVARCHAR (255) NULL,
    [ContactPhone]                     FLOAT (53)     NULL,
    [ContactPhone2]                    NVARCHAR (255) NULL,
    [Contact Address]                  NVARCHAR (255) NULL,
    [Contact City]                     NVARCHAR (255) NULL,
    [Contact State]                    NVARCHAR (255) NULL,
    [Contact Zip]                      FLOAT (53)     NULL,
    [Contact Language]                 NVARCHAR (255) NULL,
    [Contact Emergency]                NVARCHAR (255) NULL,
    [Contact Type1]                    NVARCHAR (255) NULL,
    [ROI Type1]                        NVARCHAR (255) NULL,
    [ROI Expire1]                      NVARCHAR (255) NULL,
    [Contact First1]                   NVARCHAR (255) NULL,
    [Contact Last1]                    NVARCHAR (255) NULL,
    [Contact Email1]                   NVARCHAR (255) NULL,
    [ContactPhone1]                    NVARCHAR (255) NULL,
    [ContactPhone21]                   NVARCHAR (255) NULL,
    [Contact Address1]                 NVARCHAR (255) NULL,
    [Contact City1]                    NVARCHAR (255) NULL,
    [Contact State1]                   NVARCHAR (255) NULL,
    [Contact Zip1]                     NVARCHAR (255) NULL,
    [Contact Language1]                NVARCHAR (255) NULL,
    [Contact Emergency1]               NVARCHAR (255) NULL,
    [Agency]                           NVARCHAR (255) NULL,
    [Case Manager Fname]               NVARCHAR (255) NULL,
    [Case Manager Lname]               NVARCHAR (255) NULL,
    [Email]                            NVARCHAR (255) NULL,
    [Phone]                            NVARCHAR (255) NULL,
    [Fax]                              NVARCHAR (255) NULL,
    [Care Consent]                     NVARCHAR (255) NULL,
    [Self Admin]                       NVARCHAR (255) NULL,
    [Health Info]                      NVARCHAR (255) NULL,
    [Admin Req]                        NVARCHAR (255) NULL,
    [Admin Orient]                     NVARCHAR (255) NULL,
    [Z Crisis Plan]                    NVARCHAR (255) NULL,
    [Permission for VM]                NVARCHAR (255) NULL,
    [Permission for Email]             NVARCHAR (255) NULL,
    [Permission for SMS]               NVARCHAR (255) NULL,
    [ROI to Agency]                    NVARCHAR (255) NULL,
    [Agency1]                          NVARCHAR (255) NULL,
    [Expiration]                       DATETIME       NULL,
    [Z SP R]                           NVARCHAR (255) NULL,
    [Z SP R Expiration]                DATETIME       NULL,
    [Z SP R Guardian]                  NVARCHAR (255) NULL,
    [Z SP R BHPP]                      NVARCHAR (255) NULL,
    [Z SP LS]                          NVARCHAR (255) NULL,
    [Z SP LS Expiration]               DATETIME       NULL,
    [Z SP LS Guardian]                 NVARCHAR (255) NULL,
    [Z SP LS BHPP]                     NVARCHAR (255) NULL,
    [Z SP C]                           NVARCHAR (255) NULL,
    [Z SP C Expiration]                NVARCHAR (255) NULL,
    [Z SP C Guardian]                  NVARCHAR (255) NULL,
    [Z SP C BHPP]                      NVARCHAR (255) NULL,
    [ROI from Agency]                  NVARCHAR (255) NULL,
    [Agency2]                          NVARCHAR (255) NULL,
    [Expiration Date]                  NVARCHAR (255) NULL,
    [N Crisis]                         NVARCHAR (255) NULL,
    [N SP]                             NVARCHAR (255) NULL,
    [N SP Expiration]                  DATETIME       NULL,
    [N SP Guardian]                    NVARCHAR (255) NULL,
    [N SP BHP]                         NVARCHAR (255) NULL,
    [N SP Service]                     NVARCHAR (255) NULL,
    [BX Assess]                        NVARCHAR (255) NULL,
    [BX Assess Expiration]             DATETIME       NULL,
    [BX Assess BHP]                    NVARCHAR (255) NULL,
    [DX Code]                          NVARCHAR (255) NULL,
    [DX Code Start]                    DATETIME       NULL,
    [DX Code End]                      NVARCHAR (255) NULL,
    [DX Code Prec]                     FLOAT (53)     NULL,
    [Demo]                             NVARCHAR (255) NULL,
    [Demo Expiration]                  NVARCHAR (255) NULL,
    [SNCD]                             NVARCHAR (255) NULL,
    [SNCD Date]                        DATETIME       NULL,
    [Ansell Casey Assessment]          NVARCHAR (255) NULL,
    [Ansell Casey Date]                NVARCHAR (255) NULL,
    [Payor]                            NVARCHAR (255) NULL,
    [Payor Effective]                  DATETIME       NULL,
    [Payor End]                        NVARCHAR (255) NULL,
    [Referral Date]                    DATETIME       NULL,
    [Referral Source]                  NVARCHAR (255) NULL,
    [First DOS]                        DATETIME       NULL,
    [Closure Date]                     DATETIME       NULL,
    [Closure Reason]                   NVARCHAR (255) NULL,
    [ClientStatusID]                   BIGINT         NULL,
    [ClientRegionID]                   BIGINT         NULL,
    [ClientLanguageID]                 BIGINT         NULL,
    [ClientAssigneeID]                 BIGINT         NULL,
    [ClientDropOffLocationID]          BIGINT         NULL,
    [ClientPickUpLocationID]           BIGINT         NULL,
    [ClientFrequencyCodeID]            BIGINT         NULL,
    [ClientAgencyID]                   BIGINT         NULL,
    [ClientCaseMangerID]               BIGINT         NULL,
    [ClientROITOAgencyID]              BIGINT         NULL,
    [ClientROIFromAgencyID]            BIGINT         NULL,
    [ClientPayorID]                    BIGINT         NULL,
    [ClientReferralSourceID]           BIGINT         NULL,
    [ClientDXCodeID]                   BIGINT         NULL
);

