CREATE TABLE [dbo].[EmployeeChecklists] (
    [EmployeeChecklistID]                          BIGINT         IDENTITY (1, 1) NOT NULL,
    [EmployeeID]                                   BIGINT         NOT NULL,
    [DriverLicense]                                BIT            NOT NULL,
    [StateID]                                      BIT            NOT NULL,
    [AlienCard]                                    BIT            NOT NULL,
    [Passport]                                     BIT            NOT NULL,
    [IdentificationDate]                           DATETIME       NULL,
    [IdentificationCompletionDate]                 DATETIME       NULL,
    [SSCardCopy]                                   BIT            NOT NULL,
    [SSCardDate]                                   DATETIME       NULL,
    [SSCardCompletionDate]                         DATETIME       NULL,
    [RN]                                           BIT            NOT NULL,
    [LPN]                                          BIT            NOT NULL,
    [LSW]                                          BIT            NOT NULL,
    [CNA]                                          BIT            NOT NULL,
    [Other]                                        BIT            NOT NULL,
    [OtherText]                                    NVARCHAR (100) NULL,
    [CompetencyDate]                               DATETIME       NULL,
    [CompetencyCompletionDate]                     DATETIME       NULL,
    [EducationContinuingCertificate]               BIT            NOT NULL,
    [EducationContinuingCertificateDate]           DATETIME       NULL,
    [EducationContinuingCertificateCompletionDate] DATETIME       NULL,
    [CurrentResume]                                BIT            NOT NULL,
    [CurrentResumeDate]                            DATETIME       NULL,
    [CurrentResumeCompletionDate]                  DATETIME       NULL,
    [FirstAid]                                     BIT            NOT NULL,
    [FirstAidDate]                                 DATETIME       NULL,
    [FirstAidCompletionDate]                       DATETIME       NULL,
    [CPR]                                          BIT            NOT NULL,
    [CPRDate]                                      DATETIME       NULL,
    [CPRCompletionDate]                            DATETIME       NULL,
    [BloodBornePathogens]                          BIT            NOT NULL,
    [BloodBornePathogensDate]                      DATETIME       NULL,
    [BloodBornePathogensCompletionDate]            DATETIME       NULL,
    [DriverAbstract]                               BIT            NOT NULL,
    [DriverAbstractDate]                           DATETIME       NULL,
    [DriverAbstractCompletionDate]                 DATETIME       NULL,
    [TBClearance]                                  BIT            NOT NULL,
    [TBClearanceDate]                              DATETIME       NULL,
    [TBClearanceCompletionDate]                    DATETIME       NULL,
    [HepatitisBVaccine]                            BIT            NOT NULL,
    [HepatitisBVaccineDate]                        DATETIME       NULL,
    [HepatitisBVaccineCompletionDate]              DATETIME       NULL,
    [ProtectiveServicesClearance]                  BIT            NOT NULL,
    [InitialDate]                                  DATETIME       NULL,
    [InitialCompletionDate]                        DATETIME       NULL,
    [FingerPrinting]                               BIT            NOT NULL,
    [FingerPrintingDate]                           DATETIME       NULL,
    [FingerPrintingCompletionDate]                 DATETIME       NULL,
    [YearOne]                                      INT            NULL,
    [YearTwo]                                      INT            NULL,
    [NameCheck]                                    INT            NOT NULL,
    [NameCheckDate]                                DATETIME       NULL,
    [NameCheckCompletionDate]                      DATETIME       NULL,
    [CarInsurance]                                 BIT            NOT NULL,
    [CarInsuranceDate]                             DATETIME       NULL,
    [CarInsuranceCompletionDate]                   DATETIME       NULL,
    [LiabilityInsurance]                           BIT            NOT NULL,
    [LiabilityInsuranceDate]                       DATETIME       NULL,
    [LiabilityInsuranceCompletionDate]             DATETIME       NULL,
    [EmployeeW4Form]                               BIT            NOT NULL,
    [ISCW9Form]                                    BIT            NOT NULL,
    [EmployeeFormDate]                             DATETIME       NULL,
    [EmployeeFormCompletionDate]                   DATETIME       NULL,
    [ISCGELicense]                                 BIT            NOT NULL,
    [ISCGELicenseDate]                             DATETIME       NULL,
    [ISCGELicenseCompletionDate]                   DATETIME       NULL,
    [DOHLicense]                                   BIT            NULL,
    [DOHLicenseDate]                               DATETIME       NULL,
    [DOHLicenseCompletionDate]                     DATETIME       NULL,
    [IndependentAgreement]                         BIT            NULL,
    [EmployeeAgreement]                            BIT            NULL,
    [AgreementDate]                                DATETIME       NULL,
    [AgreementCompletionDate]                      DATETIME       NULL,
    [SubmittedDate]                                DATETIME       NULL,
    [CreatedDate]                                  DATETIME       NOT NULL,
    [CreatedBy]                                    BIGINT         NOT NULL,
    [UpdatedDate]                                  DATETIME       NOT NULL,
    [UpdatedBy]                                    BIGINT         NOT NULL,
    [SystemID]                                     VARCHAR (50)   NOT NULL,
    [IsDeleted]                                    BIT            NOT NULL,
    CONSTRAINT [PK_EmployeeChecklists] PRIMARY KEY CLUSTERED ([EmployeeChecklistID] ASC)
);

