CREATE TABLE [dbo].[JO_Agencies] (
    [JO_AgencyID]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [AgencyID]                 BIGINT        NOT NULL,
    [NickName]                 VARCHAR (50)  NULL,
    [ShortName]                VARCHAR (100) NULL,
    [CompanyName]              VARCHAR (50)  NULL,
    [RegionID]                 BIGINT        NULL,
    [TaxID]                    VARCHAR (50)  NULL,
    [IsTribe]                  BIT           NULL,
    [AgencyTypeID]             BIGINT        NULL,
    [BillingGroupID]           BIGINT        NULL,
    [ContactTitle]             VARCHAR (50)  NULL,
    [ContactName]              VARCHAR (50)  NULL,
    [ContactHomePageUrl]       VARCHAR (100) NULL,
    [Email]                    VARCHAR (50)  NULL,
    [Phone]                    VARCHAR (15)  NULL,
    [Fax]                      VARCHAR (15)  NULL,
    [Address]                  VARCHAR (100) NULL,
    [City]                     VARCHAR (50)  NULL,
    [StateCode]                VARCHAR (10)  NULL,
    [ZipCode]                  VARCHAR (15)  NULL,
    [Notes]                    VARCHAR (500) NULL,
    [FiscalStartYear]          DATE          NULL,
    [FiscalEndYear]            DATE          NULL,
    [RespiteHours]             INT           NULL,
    [AgencyPrefix]             VARCHAR (2)   NULL,
    [InsuranceCompanyName]     VARCHAR (100) NULL,
    [InsuranceCompanyAddress1] VARCHAR (100) NULL,
    [InsuranceCompanyAddress2] VARCHAR (100) NULL,
    [InsuranceCompanyCSZ]      VARCHAR (100) NULL,
    [InsuranceTypeID]          BIGINT        NULL,
    [IsUseCortexForBilling]    BIT           NULL,
    [IsMultipleLocation]       BIT           NULL,
    [IsUsesAuthorization]      BIT           NULL,
    [Action]                   CHAR (1)      NOT NULL,
    [ActionDate]               DATETIME      NOT NULL,
    [IsDeleted]                BIT           CONSTRAINT [DF_JO_Agencies_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedDate]              DATETIME      NULL,
    [CreatedBy]                BIGINT        NULL,
    [UpdatedDate]              DATETIME      NULL,
    [UpdatedBy]                BIGINT        NULL,
    [SystemID]                 VARCHAR (100) NULL,
    CONSTRAINT [PK_JO_Agencies] PRIMARY KEY CLUSTERED ([JO_AgencyID] ASC)
);

