CREATE TABLE [dbo].[JO_Facilities] (
    [JO_FacilityID]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [FacilityID]              BIGINT        NOT NULL,
    [FacilityName]            VARCHAR (100) NULL,
    [FacilityBillingName]     VARCHAR (100) NULL,
    [Address]                 VARCHAR (100) NULL,
    [City]                    VARCHAR (50)  NULL,
    [State]                   VARCHAR (10)  NULL,
    [ZipCode]                 VARCHAR (15)  NULL,
    [Phone]                   VARCHAR (15)  NULL,
    [Cell]                    VARCHAR (15)  NULL,
    [RegionID]                BIGINT        NULL,
    [County]                  VARCHAR (50)  NULL,
    [GSA]                     INT           NULL,
    [BadCapacity]             INT           NULL,
    [PrivateRoomCount]        INT           NULL,
    [SiteType]                VARCHAR (100) NULL,
    [ProviderType]            VARCHAR (50)  NULL,
    [Licensure]               VARCHAR (100) NULL,
    [LicensureRenewalDate]    DATE          NULL,
    [FirePermitDate]          DATE          NULL,
    [NPI]                     VARCHAR (10)  NULL,
    [AHCCCSID]                VARCHAR (6)   NULL,
    [EIN]                     VARCHAR (9)   NULL,
    [FacilityColorScheme]     VARCHAR (10)  NULL,
    [ParentFacilityID]        BIGINT        NULL,
    [CreatedBy]               BIGINT        NOT NULL,
    [CreatedDate]             DATETIME      NOT NULL,
    [UpdatedDate]             DATETIME      NOT NULL,
    [UpdatedBy]               BIGINT        NOT NULL,
    [IsDeleted]               BIT           NOT NULL,
    [SystemID]                VARCHAR (50)  NOT NULL,
    [Action]                  CHAR (1)      NOT NULL,
    [ActionDate]              DATETIME      NOT NULL,
    [DefaultScheduleStatusID] BIGINT        NULL,
    CONSTRAINT [PK_JO_Facilities] PRIMARY KEY CLUSTERED ([JO_FacilityID] ASC)
);

