CREATE TABLE [dbo].[MIFDetails] (
    [MIFFormID]                          BIGINT         IDENTITY (1, 1) NOT NULL,
    [ReferralID]                         BIGINT         NOT NULL,
    [FromWhoToWho]                       NVARCHAR (50)  NULL,
    [Type]                               NVARCHAR (20)  NULL,
    [IsResponseRequired]                 BIT            NULL,
    [ServiceType_AHD]                    BIT            NULL,
    [ServiceType_ALS]                    BIT            NULL,
    [ServiceType_ERS]                    BIT            NULL,
    [ServiceType_HDM]                    BIT            NULL,
    [ServiceType_HDS]                    BIT            NULL,
    [ServiceType_PSS]                    BIT            NULL,
    [ServiceType_EPS]                    BIT            NULL,
    [IsInitialServiceOffered]            BIT            NULL,
    [InitialServiceNoReason]             NVARCHAR (MAX) NULL,
    [InitialServiceDate]                 DATE           NULL,
    [InitialServiceFrequencyID]          BIGINT         NULL,
    [ChangeFYI_RecommendationForChange]  BIT            NULL,
    [ChangeFYI_ChangeInHealthFuncStatus] BIT            NULL,
    [ChangeFYI_Hospitalization]          BIT            NULL,
    [ChangeFYI_ServiceNotDelivered]      BIT            NULL,
    [ChangeFYI_ChangeInFrequencyByCM]    BIT            NULL,
    [ChangeFYI_ChangeInPhysician]        BIT            NULL,
    [ChangeFYI_Other]                    BIT            NULL,
    [ChangeFYI_FYI]                      BIT            NULL,
    [Explanation]                        NVARCHAR (MAX) NULL,
    [EffectiveDateOfChange]              DATE           NULL,
    [DischargeReason]                    NVARCHAR (MAX) NULL,
    [DateOfDischarge]                    DATE           NULL,
    [Comments]                           NVARCHAR (MAX) NULL,
    [PriorAuthorizationDateFrom]         DATE           NULL,
    [PriorAuthorizationDateTo]           DATE           NULL,
    [PriorAuthorizationNo]               NVARCHAR (200) NULL,
    [SignaturePath]                      NVARCHAR (MAX) NULL,
    [IsDeleted]                          BIT            CONSTRAINT [DF_MIFDetails_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedDate]                        DATETIME       NULL,
    [CreatedBy]                          BIGINT         NULL,
    [UpdatedDate]                        DATETIME       NULL,
    [UpdatedBy]                          BIGINT         NULL,
    [SystemID]                           VARCHAR (100)  NULL,
    [FormName]                           NVARCHAR (200) NULL,
    CONSTRAINT [PK_MIFDetails] PRIMARY KEY CLUSTERED ([MIFFormID] ASC)
);

