CREATE TABLE [dbo].[ReferralCheckLists] (
    [ReferralCheckListID]                       BIGINT        IDENTITY (1, 1) NOT NULL,
    [ServiceRequested]                          BIT           NOT NULL,
    [RespiteService]                            BIT           NOT NULL,
    [LifeSkillsService]                         BIT           NOT NULL,
    [CounselingService]                         BIT           NOT NULL,
    [FacilitatorContacted]                      BIT           NOT NULL,
    [FacilitatorContactedText]                  VARCHAR (100) NULL,
    [AHCCCSVerification]                        BIT           NOT NULL,
    [AHCCCSVerificationText]                    DATE          NULL,
    [ASPRespiteIntervention]                    VARCHAR (2)   NULL,
    [ASPRespiteInterventionText]                VARCHAR (100) NULL,
    [SPExpireAndGuardianBHPSigned]              BIT           NOT NULL,
    [SPExpireAndGuardianBHPSignedText]          DATE          NULL,
    [SPSignedByBHP]                             BIT           NOT NULL,
    [SPSignedByBHPText]                         VARCHAR (100) NULL,
    [SPSignedByGuardian]                        BIT           NOT NULL,
    [SPSignedByGuardianText]                    VARCHAR (100) NULL,
    [CoreAssessmentORAnnualUpdateCompleted]     BIT           NOT NULL,
    [CoreAssessmentORAnnualUpdateCompletedText] DATE          NULL,
    [DiagnosisCodes]                            BIT           NOT NULL,
    [DiagnosisCodesText]                        VARCHAR (100) NULL,
    [AssessmentBHPSigned]                       BIT           NOT NULL,
    [AssessmentBHPSignedChecked]                BIT           NULL,
    [SNCD]                                      VARCHAR (100) NULL,
    [SNCDText]                                  DATE          NULL,
    [Demographics]                              VARCHAR (100) NULL,
    [DemographicsText]                          DATE          NULL,
    [ROI]                                       VARCHAR (100) NULL,
    [ROIText]                                   VARCHAR (100) NULL,
    [ReferralChecklist]                         BIT           NOT NULL,
    [ReferralChecklistText]                     VARCHAR (100) NULL,
    [RequestPaperWork]                          BIT           NOT NULL,
    [RequestPaperWorkText]                      VARCHAR (100) NULL,
    [PaperWorkReceived]                         BIT           NOT NULL,
    [PaperWorkReceivedText]                     VARCHAR (100) NULL,
    [Notes]                                     VARCHAR (500) NULL,
    [IsCheckListCompleted]                      BIT           NOT NULL,
    [ChecklistCompletedBy]                      BIGINT        NULL,
    [ChecklistCompletedDate]                    DATETIME      NULL,
    [ReferralID]                                BIGINT        NOT NULL,
    [CreatedDate]                               DATETIME      NOT NULL,
    [CreatedBy]                                 BIGINT        NOT NULL,
    [UpdatedDate]                               DATETIME      NOT NULL,
    [UpdatedBy]                                 BIGINT        NOT NULL,
    [SystemID]                                  VARCHAR (100) NOT NULL,
    [IsCheckListOffline]                        BIT           NULL,
    [ConnectingFamiliesService]                 BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ReferralCheckLists] PRIMARY KEY CLUSTERED ([ReferralCheckListID] ASC),
    CONSTRAINT [FK_ReferralCheckLists_ReferralCheckLists] FOREIGN KEY ([ReferralID]) REFERENCES [dbo].[Referrals] ([ReferralID])
);


GO
CREATE TRIGGER [dbo].[tr_ReferralCheckLists_Deleted] ON dbo.ReferralCheckLists
FOR Delete AS 

INSERT INTO JO_ReferralCheckLists( 
ReferralCheckListID,
ServiceRequested,
RespiteService,
LifeSkillsService,
CounselingService,
FacilitatorContacted,
FacilitatorContactedText,
AHCCCSVerification,
AHCCCSVerificationText,
ASPRespiteIntervention,
ASPRespiteInterventionText,
SPExpireAndGuardianBHPSigned,
SPExpireAndGuardianBHPSignedText,
CoreAssessmentORAnnualUpdateCompleted,
CoreAssessmentORAnnualUpdateCompletedText,
DiagnosisCodes,
DiagnosisCodesText,
AssessmentBHPSigned,
AssessmentBHPSignedChecked,
SNCD,
SNCDText,
Demographics,
DemographicsText,
ROI,
ROIText,
ReferralChecklist,
ReferralChecklistText,
RequestPaperWork,
RequestPaperWorkText,
PaperWorkReceived,
PaperWorkReceivedText,
Notes,
IsCheckListCompleted,
ChecklistCompletedBy,
ChecklistCompletedDate,
ReferralID,
CreatedDate,
CreatedBy,
UpdatedDate,
UpdatedBy,
SystemID,
Action,ActionDate,
SPSignedByBHP,
SPSignedByBHPText,
SPSignedByGuardian,
SPSignedByGuardianText,
IsCheckListOffline
)

SELECT  
ReferralCheckListID,
ServiceRequested,
RespiteService,
LifeSkillsService,
CounselingService,
FacilitatorContacted,
FacilitatorContactedText,
AHCCCSVerification,
AHCCCSVerificationText,
ASPRespiteIntervention,
ASPRespiteInterventionText,
SPExpireAndGuardianBHPSigned,
SPExpireAndGuardianBHPSignedText,
CoreAssessmentORAnnualUpdateCompleted,
CoreAssessmentORAnnualUpdateCompletedText,
DiagnosisCodes,
DiagnosisCodesText,
AssessmentBHPSigned,
AssessmentBHPSignedChecked,
SNCD,
SNCDText,
Demographics,
DemographicsText,
ROI,
ROIText,
ReferralChecklist,
ReferralChecklistText,
RequestPaperWork,
RequestPaperWorkText,
PaperWorkReceived,
PaperWorkReceivedText,
Notes,
IsCheckListCompleted,
ChecklistCompletedBy,
ChecklistCompletedDate,
ReferralID,
CreatedDate,
CreatedBy,
UpdatedDate,
UpdatedBy,
SystemID,
'D',GETUTCDATE(),
SPSignedByBHP,
SPSignedByBHPText,
SPSignedByGuardian,
SPSignedByGuardianText,
IsCheckListOffline FROM deleted

GO
CREATE TRIGGER [dbo].[tr_ReferralCheckLists_Updated] ON dbo.ReferralCheckLists
FOR UPDATE AS 

INSERT INTO JO_ReferralCheckLists( 
ReferralCheckListID,
ServiceRequested,
RespiteService,
LifeSkillsService,
CounselingService,
FacilitatorContacted,
FacilitatorContactedText,
AHCCCSVerification,
AHCCCSVerificationText,
ASPRespiteIntervention,
ASPRespiteInterventionText,
SPExpireAndGuardianBHPSigned,
SPExpireAndGuardianBHPSignedText,
CoreAssessmentORAnnualUpdateCompleted,
CoreAssessmentORAnnualUpdateCompletedText,
DiagnosisCodes,
DiagnosisCodesText,
AssessmentBHPSigned,
AssessmentBHPSignedChecked,
SNCD,
SNCDText,
Demographics,
DemographicsText,
ROI,
ROIText,
ReferralChecklist,
ReferralChecklistText,
RequestPaperWork,
RequestPaperWorkText,
PaperWorkReceived,
PaperWorkReceivedText,
Notes,
IsCheckListCompleted,
ChecklistCompletedBy,
ChecklistCompletedDate,
ReferralID,
CreatedDate,
CreatedBy,
UpdatedDate,
UpdatedBy,
SystemID,
Action,ActionDate,
SPSignedByBHP,
SPSignedByBHPText,
SPSignedByGuardian,
SPSignedByGuardianText,
IsCheckListOffline
)

SELECT  
ReferralCheckListID,
ServiceRequested,
RespiteService,
LifeSkillsService,
CounselingService,
FacilitatorContacted,
FacilitatorContactedText,
AHCCCSVerification,
AHCCCSVerificationText,
ASPRespiteIntervention,
ASPRespiteInterventionText,
SPExpireAndGuardianBHPSigned,
SPExpireAndGuardianBHPSignedText,
CoreAssessmentORAnnualUpdateCompleted,
CoreAssessmentORAnnualUpdateCompletedText,
DiagnosisCodes,
DiagnosisCodesText,
AssessmentBHPSigned,
AssessmentBHPSignedChecked,
SNCD,
SNCDText,
Demographics,
DemographicsText,
ROI,
ROIText,
ReferralChecklist,
ReferralChecklistText,
RequestPaperWork,
RequestPaperWorkText,
PaperWorkReceived,
PaperWorkReceivedText,
Notes,
IsCheckListCompleted,
ChecklistCompletedBy,
ChecklistCompletedDate,
ReferralID,
CreatedDate,
CreatedBy,
UpdatedDate,
UpdatedBy,
SystemID,
'U',GETUTCDATE(),
SPSignedByBHP,
SPSignedByBHPText,
SPSignedByGuardian,
SPSignedByGuardianText,
IsCheckListOffline
 FROM deleted
