//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeCareApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeCareApi.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is required.
        /// </summary>
        internal static string ActionRequired {
            get {
                return ResourceManager.GetString("ActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there looks some problem with your request, such as a missing, invalid or type mismatched parameter.
        /// </summary>
        internal static string BadRequestMessage {
            get {
                return ResourceManager.GetString("BadRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByPass Clock In.
        /// </summary>
        internal static string ByPassClockIn {
            get {
                return ResourceManager.GetString("ByPassClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Pass Clock In Notification.
        /// </summary>
        internal static string ByPassClockInNotification {
            get {
                return ResourceManager.GetString("ByPassClockInNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByPass Clock Out.
        /// </summary>
        internal static string ByPassClockOut {
            get {
                return ResourceManager.GetString("ByPassClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Pass Clock Out Notification.
        /// </summary>
        internal static string ByPassClockOutNotification {
            get {
                return ResourceManager.GetString("ByPassClockOutNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockIn.
        /// </summary>
        internal static string ClockIn {
            get {
                return ResourceManager.GetString("ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockIn Failed, Geographical Coordinates Mismatch.
        /// </summary>
        internal static string ClockInFailed {
            get {
                return ResourceManager.GetString("ClockInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock In time must be lesser than schedule end time.
        /// </summary>
        internal static string ClockInLesserThanScheduleEnd {
            get {
                return ResourceManager.GetString("ClockInLesserThanScheduleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock In/Out Time added successfully.
        /// </summary>
        internal static string ClockInOutLogAddedSuccessfully {
            get {
                return ResourceManager.GetString("ClockInOutLogAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock In/Out Time updated successfully.
        /// </summary>
        internal static string ClockInOutTimeUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ClockInOutTimeUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockIn Successfully.
        /// </summary>
        internal static string ClockInSuccessfully {
            get {
                return ResourceManager.GetString("ClockInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockOut.
        /// </summary>
        internal static string ClockOut {
            get {
                return ResourceManager.GetString("ClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockOut Failed, Geographical Coordinates Mismatch.
        /// </summary>
        internal static string ClockOutFailed {
            get {
                return ResourceManager.GetString("ClockOutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock out time must be greater than Clock In time.
        /// </summary>
        internal static string ClockOutGreaterThanClockIn {
            get {
                return ResourceManager.GetString("ClockOutGreaterThanClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClockOut Successfully.
        /// </summary>
        internal static string ClockOutSuccessfully {
            get {
                return ResourceManager.GetString("ClockOutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Not Found.
        /// </summary>
        internal static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the required task/s before Clock Out.
        /// </summary>
        internal static string CompleteRequiredTask {
            get {
                return ResourceManager.GetString("CompleteRequiredTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusion Added Succesfully.
        /// </summary>
        internal static string ConclusionAddedSuccesfully {
            get {
                return ResourceManager.GetString("ConclusionAddedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Successfully.
        /// </summary>
        internal static string CreatedSuccessfully {
            get {
                return ResourceManager.GetString("CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fetched successfully..
        /// </summary>
        internal static string DataFetchedSuccessfully {
            get {
                return ResourceManager.GetString("DataFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Off created successfully.
        /// </summary>
        internal static string DayOffCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DayOffCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Off deleted successfully.
        /// </summary>
        internal static string DayOffDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DayOffDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Off updated successfully.
        /// </summary>
        internal static string DayOffUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DayOffUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        internal static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Saved Successfully.
        /// </summary>
        internal static string DetailSaveSuccessfully {
            get {
                return ResourceManager.GetString("DetailSaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type is required.
        /// </summary>
        internal static string DeviceTypeRequired {
            get {
                return ResourceManager.GetString("DeviceTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Deleted Successfully..
        /// </summary>
        internal static string DocumentDeleted {
            get {
                return ResourceManager.GetString("DocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but their is an error while saving your documents..
        /// </summary>
        internal static string DocumentTransferError {
            get {
                return ResourceManager.GetString("DocumentTransferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document type has already been used.
        /// </summary>
        internal static string DocumentTypeExists {
            get {
                return ResourceManager.GetString("DocumentTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Updated.
        /// </summary>
        internal static string DocumentUpdated {
            get {
                return ResourceManager.GetString("DocumentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  but their is an error while saving your documents..
        /// </summary>
        internal static string DocumentUploadError {
            get {
                return ResourceManager.GetString("DocumentUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Uploaded Successfully.
        /// </summary>
        internal static string DocumentUploadSuccessfully {
            get {
                return ResourceManager.GetString("DocumentUploadSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, record with same {0} already exists.
        /// </summary>
        internal static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Clock In not allowed..
        /// </summary>
        internal static string EarlyClockInMessage {
            get {
                return ResourceManager.GetString("EarlyClockInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early ClockOut.
        /// </summary>
        internal static string EarlyClockOut {
            get {
                return ResourceManager.GetString("EarlyClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Clock Out Notification.
        /// </summary>
        internal static string EarlyClockOutNotification {
            get {
                return ResourceManager.GetString("EarlyClockOutNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to the schedule for which the shift end time is past the current time, if you feel this message in error , please contact your office administrator.
        /// </summary>
        internal static string exceededClockouttimeLimit {
            get {
                return ResourceManager.GetString("exceededClockouttimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops something went wrong. We are working on this. Please try after some time..
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is Required.
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deleted successfully..
        /// </summary>
        internal static string FileDeleteSuccess {
            get {
                return ResourceManager.GetString("FileDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not selected.
        /// </summary>
        internal static string FileNotSelected {
            get {
                return ResourceManager.GetString("FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Saved Successfully.
        /// </summary>
        internal static string FormSavedSuccessfully {
            get {
                return ResourceManager.GetString("FormSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Notification.
        /// </summary>
        internal static string GeneralNotification {
            get {
                return ResourceManager.GetString("GeneralNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocordinate Updated Successfully.
        /// </summary>
        internal static string GeocordinateUpdateSuccessfully {
            get {
                return ResourceManager.GetString("GeocordinateUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Uploaded Successfully.
        /// </summary>
        internal static string ImageUploadedSuccessfully {
            get {
                return ResourceManager.GetString("ImageUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked. Please contact the administrator..
        /// </summary>
        internal static string InactiveAccount {
            get {
                return ResourceManager.GetString("InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please try again later or click on forgot password to reset password..
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent Successfully.
        /// </summary>
        internal static string InternalMessageSent {
            get {
                return ResourceManager.GetString("InternalMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Already Exists.
        /// </summary>
        internal static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivr code not found.
        /// </summary>
        internal static string IvrCodeNotFound {
            get {
                return ResourceManager.GetString("IvrCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key validate successfully.
        /// </summary>
        internal static string KeyValidateSuccess {
            get {
                return ResourceManager.GetString("KeyValidateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged in.
        /// </summary>
        internal static string LoginSuccessfully {
            get {
                return ResourceManager.GetString("LoginSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can upload maximum of {0} files only.
        /// </summary>
        internal static string MaxFileUploadSizeExceded {
            get {
                return ResourceManager.GetString("MaxFileUploadSizeExceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message resovled successfully.
        /// </summary>
        internal static string MessageResolved {
            get {
                return ResourceManager.GetString("MessageResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Patient Geographical Coordinates.
        /// </summary>
        internal static string MissingPatientCoordinates {
            get {
                return ResourceManager.GetString("MissingPatientCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Employee with this Mobile Number already exists in the system. Please try another Mobile Number..
        /// </summary>
        internal static string MobileNumberExist {
            get {
                return ResourceManager.GetString("MobileNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is required.
        /// </summary>
        internal static string MobileRequired {
            get {
                return ResourceManager.GetString("MobileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is missing or invalid.
        /// </summary>
        internal static string MSG_KeyMissingInvalid {
            get {
                return ResourceManager.GetString("MSG_KeyMissingInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email.
        /// </summary>
        internal static string NoEmailIdSet {
            get {
                return ResourceManager.GetString("NoEmailIdSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template not found. Please contact administrator..
        /// </summary>
        internal static string NoEmailTemplateFound {
            get {
                return ResourceManager.GetString("NoEmailTemplateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no notifications for you.
        /// </summary>
        internal static string NoNotificationShow {
            get {
                return ResourceManager.GetString("NoNotificationShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note added successfully.
        /// </summary>
        internal static string NoteAddedSuccessfully {
            get {
                return ResourceManager.GetString("NoteAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note deleted successfully.
        /// </summary>
        internal static string NoteDeletedSuccessfully {
            get {
                return ResourceManager.GetString("NoteDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note updated successfully.
        /// </summary>
        internal static string NoteUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("NoteUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Archieved.
        /// </summary>
        internal static string NotificationArchieved {
            get {
                return ResourceManager.GetString("NotificationArchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Deleted.
        /// </summary>
        internal static string NotificationDeleted {
            get {
                return ResourceManager.GetString("NotificationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications processed successfully.
        /// </summary>
        internal static string NotificationListBindSuccessfully {
            get {
                return ResourceManager.GetString("NotificationListBindSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Process.
        /// </summary>
        internal static string NotProcess {
            get {
                return ResourceManager.GetString("NotProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp is expired. please resend Otp and try again..
        /// </summary>
        internal static string OtpExpired {
            get {
                return ResourceManager.GetString("OtpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP for the EVVApp is: .
        /// </summary>
        internal static string OTPMessage {
            get {
                return ResourceManager.GetString("OTPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,&lt;/br&gt; Your OTP for the EVVApp is:.
        /// </summary>
        internal static string OTPMessageEmail {
            get {
                return ResourceManager.GetString("OTPMessageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp is required.
        /// </summary>
        internal static string OtpRequired {
            get {
                return ResourceManager.GetString("OtpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp sent successfully.
        /// </summary>
        internal static string OtpSentSuccessfully {
            get {
                return ResourceManager.GetString("OtpSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp verified successfully.
        /// </summary>
        internal static string OtpVerified {
            get {
                return ResourceManager.GetString("OtpVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        internal static string PasswordChangeMessage {
            get {
                return ResourceManager.GetString("PasswordChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Resignature.
        /// </summary>
        internal static string PatientResignature {
            get {
                return ResourceManager.GetString("PatientResignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference stored successfully..
        /// </summary>
        internal static string PreferenceStoredSuccessfully {
            get {
                return ResourceManager.GetString("PreferenceStoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, record with same {0} already exists.
        /// </summary>
        internal static string RecordAlreadyExists {
            get {
                return ResourceManager.GetString("RecordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, record with same {0} combined already exists.
        /// </summary>
        internal static string RecordCombinedAlreadyExists {
            get {
                return ResourceManager.GetString("RecordCombinedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully.
        /// </summary>
        internal static string RecordSavedSuccessfully {
            get {
                return ResourceManager.GetString("RecordSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral.
        /// </summary>
        internal static string Referral {
            get {
                return ResourceManager.GetString("Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Accepted.
        /// </summary>
        internal static string ScheduleAccepted {
            get {
                return ResourceManager.GetString("ScheduleAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Created Successfully.
        /// </summary>
        internal static string ScheduleCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ScheduleCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Added Successfully.
        /// </summary>
        internal static string SectionAddedSuccessfully {
            get {
                return ResourceManager.GetString("SectionAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Updated Successfully.
        /// </summary>
        internal static string SectionUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SectionUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Schedule Notification.
        /// </summary>
        internal static string SendScheduleNotification {
            get {
                return ResourceManager.GetString("SendScheduleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error - .
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service denied successfully.
        /// </summary>
        internal static string ServiceDeniedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceDeniedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Time must be greater than.
        /// </summary>
        internal static string ServiceGreaterThan {
            get {
                return ResourceManager.GetString("ServiceGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Transaction Error - .
        /// </summary>
        internal static string SqlTransactionError {
            get {
                return ResourceManager.GetString("SqlTransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Section Added Successfully.
        /// </summary>
        internal static string SubSectionAddedSuccessfully {
            get {
                return ResourceManager.GetString("SubSectionAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Section Updated Successfully.
        /// </summary>
        internal static string SubSectionUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SubSectionUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Added Successfully.
        /// </summary>
        internal static string TaskAddedSuccessfully {
            get {
                return ResourceManager.GetString("TaskAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task deleted successfully.
        /// </summary>
        internal static string TaskDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TaskDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expired or same user logged in another device..
        /// </summary>
        internal static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total service time are exceeding.
        /// </summary>
        internal static string TotalTimeExceeded {
            get {
                return ResourceManager.GetString("TotalTimeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        internal static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the given mobile number does not exists.
        /// </summary>
        internal static string UserDoesNotExists {
            get {
                return ResourceManager.GetString("UserDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged out successfully.
        /// </summary>
        internal static string UserLoggedOutSuccessfully {
            get {
                return ResourceManager.GetString("UserLoggedOutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, user with this username already exists in the system. Please try another username..
        /// </summary>
        internal static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid username.
        /// </summary>
        internal static string UsernameNotValid {
            get {
                return ResourceManager.GetString("UsernameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, We didn&apos;t recognize that username and password/pin combination. please double-check and try again..
        /// </summary>
        internal static string UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit time must be greater than service time..
        /// </summary>
        internal static string VisitTimeGreaterThanServiceTime {
            get {
                return ResourceManager.GetString("VisitTimeGreaterThanServiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct OTP and try again later.
        /// </summary>
        internal static string WrongOtp {
            get {
                return ResourceManager.GetString("WrongOtp", resourceCulture);
            }
        }
    }
}
