

CREATE TRIGGER [dbo].[tr_Referrals_Updated] ON [dbo].[Referrals]
FOR UPDATE AS 
Declare @Cnt int
select @cnt=isDeleted from inserted
--print @Cnt
IF(@cnt= 1)
BEGIN

	UPDATE Referrals SET ReferralStatusID=3 WHERE ReferralID in (SELECT TOP 1 ReferralID FROM deleted) 
	DELETE FROM ScheduleMasters WHERE ReferralID IN (SELECT TOP 1 ReferralID FROM deleted)  AND StartDate >= GETDATE()
END

INSERT INTO JO_Referrals( 
ReferralID,
Title,
FirstName,
MiddleName,
LastName,
Dob	,
Gender,
RecordRequestEmail,
LanguageID	,
ClientNumber,	
AHCCCSID	,
CISNumber	,
Population	,
HealthPlan	,
RateCode	,
RateCodeStartDate,
RateCodeEndDate,
AHCCCSEnrollDate,
PlacementRequirement,
BehavioralIssue,
OtherInformation,
AgencyID,
AgencyLocationID,
CaseManagerID,
FirstDOS,
ReferralDate,
ClosureDate,
ClosureReason,
CareConsent,
SelfAdministrationofMedication,
HealthInformationDisclosure,
AdmissionRequirements,
AdmissionOrientation,
ZarephathCrisisPlan,
NetworkCrisisPlan,
NCPExpirationDate,
PermissionForVoiceMail,
PermissionForEmail,
PermissionForSMS,
AROI,
AROIAgencyID,
AROIExpirationDate,
PHI,
PHIAgencyID,
PHIExpirationDate,
ZSPRespite,
ZSPRespiteExpirationDate,
ZSPRespiteGuardianSignature,
ZSPRespiteBHPSigned,
ZSPLifeSkills,
ZSPLifeSkillsExpirationDate,
ZSPLifeSkillsGuardianSignature,
ZSPLifeSkillsBHPSigned,
ZSPCounselling,
ZSPCounsellingExpirationDate,
ZSPCounsellingGuardianSignature,
ZSPCounsellingBHPSigned,
NetworkServicePlan,
NSPExpirationDate,
NSPGuardianSignature,
NSPBHPSigned,
NSPSPidentifyService,
BXAssessment,
BXAssessmentExpirationDate,
BXAssessmentBHPSigned,
Demographic,
DemographicExpirationDate,
SNCD,
SNCDExpirationDate,
ACAssessment,
ACAssessmentExpirationDate,
IsCheckListCompleted,
IsSparFormCompleted,
IsSaveAsDraft,
ReferralStatusID,
Assignee,
DropOffLocation,
PickUpLocation,
NeedPrivateRoom,
OrientationDate,
FrequencyCodeID,
ClientID,
CreatedDate,
CreatedBy,
UpdatedDate,
UpdatedBy,
SystemID,
IsDeleted,
RegionID,
NotifyCaseManager,
LastAttendedDate,
ReferralSourceID,
Action,ActionDate,ClientNickName,ScheduleRequestDates
)

SELECT  
ReferralID,
Title,
FirstName,
MiddleName,
LastName,
Dob	,
Gender,
RecordRequestEmail,
LanguageID	,
ClientNumber,	
AHCCCSID	,
CISNumber	,
Population	,
HealthPlan	,
RateCode	,
RateCodeStartDate,
RateCodeEndDate,
AHCCCSEnrollDate,
PlacementRequirement,
BehavioralIssue,
OtherInformation,
AgencyID,
AgencyLocationID,
CaseManagerID,
FirstDOS,
ReferralDate,
ClosureDate,
ClosureReason,
CareConsent,
SelfAdministrationofMedication,
HealthInformationDisclosure,
AdmissionRequirements,
AdmissionOrientation,
ZarephathCrisisPlan,
NetworkCrisisPlan,
NCPExpirationDate,
PermissionForVoiceMail,
PermissionForEmail,
PermissionForSMS,
AROI,
AROIAgencyID,
AROIExpirationDate,
PHI,
PHIAgencyID,
PHIExpirationDate,
ZSPRespite,
ZSPRespiteExpirationDate,
ZSPRespiteGuardianSignature,
ZSPRespiteBHPSigned,
ZSPLifeSkills,
ZSPLifeSkillsExpirationDate,
ZSPLifeSkillsGuardianSignature,
ZSPLifeSkillsBHPSigned,
ZSPCounselling,
ZSPCounsellingExpirationDate,
ZSPCounsellingGuardianSignature,
ZSPCounsellingBHPSigned,
NetworkServicePlan,
NSPExpirationDate,
NSPGuardianSignature,
NSPBHPSigned,
NSPSPidentifyService,
BXAssessment,
BXAssessmentExpirationDate,
BXAssessmentBHPSigned,
Demographic,
DemographicExpirationDate,
SNCD,
SNCDExpirationDate,
ACAssessment,
ACAssessmentExpirationDate,
IsCheckListCompleted,
IsSparFormCompleted,
IsSaveAsDraft,
ReferralStatusID,
Assignee,
DropOffLocation,
PickUpLocation,
NeedPrivateRoom,
OrientationDate,
FrequencyCodeID,
ClientID,
CreatedDate,
CreatedBy,
UpdatedDate,
UpdatedBy,
SystemID,
IsDeleted,
RegionID,
NotifyCaseManager,
LastAttendedDate,
ReferralSourceID,
'U',GETUTCDATE(),ClientNickName,
ScheduleRequestDates
 FROM deleted