CREATE TABLE [dbo].[Invoice] (
    [InvoiceNumber]             BIGINT          IDENTITY (1000, 1) NOT NULL,
    [OrganizationId]            BIGINT          NULL,
    [InvoiceDate]               DATETIME        NOT NULL,
    [PlanName]                  NVARCHAR (50)   NULL,
    [DueDate]                   DATETIME        NULL,
    [ActivePatientQuantity]     INT             NOT NULL,
    [ActivePatientUnit]         DECIMAL (18, 3) NULL,
    [ActivePatientAmount]       DECIMAL (18, 3) NULL,
    [NumberOfTimeSheetQuantity] INT             NULL,
    [NumberOfTimeSheetUnit]     DECIMAL (18, 3) NULL,
    [NumberOfTimeSheetAmount]   DECIMAL (18, 3) NULL,
    [IVRQuantity]               INT             NULL,
    [IVRUnit]                   DECIMAL (18, 3) NULL,
    [IVRAmount]                 DECIMAL (18, 3) NULL,
    [MessageQuantity]           INT             NULL,
    [MessageUnit]               DECIMAL (18, 3) NULL,
    [MessageAmount]             DECIMAL (18, 3) NULL,
    [ClaimsQuantity]            INT             NULL,
    [ClaimsUnit]                DECIMAL (18, 3) NULL,
    [ClaimsAmount]              DECIMAL (18, 3) NULL,
    [FormsQuantity]             INT             NULL,
    [FormsUnit]                 DECIMAL (18, 3) NULL,
    [FormsAmount]               DECIMAL (18, 3) NULL,
    [InvoiceStatus]             NVARCHAR (50)   NULL,
    [Status]                    BIT             NULL,
    [IsPaid]                    BIT             NULL,
    [PaymentDate]               DATETIME        NULL,
    [CreatedDate]               DATETIME        NULL,
    [UpdatedDate]               DATETIME        NULL,
    [MonthId]                   INT             NULL,
    [PaidAmount]                DECIMAL (18, 3) NULL,
    [InvoiceAmount]             DECIMAL (18, 3) NULL,
    [FilePath]                  NVARCHAR (200)  NULL,
    [OrginalFileName]           NVARCHAR (500)  NULL,
    PRIMARY KEY CLUSTERED ([InvoiceNumber] ASC)
);

