CREATE TABLE [dbo].[Organizations] (
    [OrganizationID]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [DisplayName]           NVARCHAR (100) NULL,
    [CompanyName]           NVARCHAR (100) NOT NULL,
    [DomainName]            NVARCHAR (100) NULL,
    [DBServer]              NVARCHAR (200) NULL,
    [DBName]                NVARCHAR (200) NULL,
    [DBUserName]            NVARCHAR (200) NULL,
    [DBPassword]            NVARCHAR (MAX) NULL,
    [DBProviderName]        NVARCHAR (200) NULL,
    [StartDate]             DATETIME       NULL,
    [EndDate]               DATETIME       NULL,
    [IsActive]              BIT            NOT NULL,
    [OrganizationType]      NVARCHAR (100) CONSTRAINT [DF__Organizat__Organ__4AB81AF0] DEFAULT ('HomeCare') NULL,
    [Email]                 NVARCHAR (100) NULL,
    [Mobile]                NVARCHAR (20)  NULL,
    [WorkPhone]             NVARCHAR (20)  NULL,
    [DefaultEsignTerms]     NVARCHAR (MAX) NULL,
    [OrganizationStatusID]  BIGINT         NULL,
    [SuitCRMID]             NVARCHAR (100) NULL,
    [OrganizationTypeID]    BIGINT         NULL,
    [CreatedBy]             BIGINT         NULL,
    [CreatedDate]           DATETIME       NULL,
    [UpdatedDate]           DATETIME       NULL,
    [UpdatedBy]             BIGINT         NULL,
    [SystemID]              VARCHAR (100)  NULL,
    [IsDeleted]             BIT            CONSTRAINT [DF_Organizations_IsDeleted] DEFAULT ((0)) NULL,
    [LastFormSyncDate]      DATETIME       NULL,
    [iOSAppDownloadURL]     VARCHAR (MAX)  NULL,
    [AndroidAppDownloadURL] VARCHAR (MAX)  NULL,
    [IsCompletedWizard]     BIT            CONSTRAINT [DF_Organizations_IsCompletedWizard] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Organizations] PRIMARY KEY CLUSTERED ([OrganizationID] ASC)
);

